/*
 * tkWaylandKey.c –
 *
 * This file contains functions for keyboard input handling on Wayland/GLFW,
 * including comprehensive IME (Input Method Editor) support for complex text
 * input (Chinese, Japanese, Korean, etc.).
 *
 * Copyright © 2026 Kevin Walzer
 * Copyright © 2026 Marc Culler
 *
 * See the file "license.terms" for information on usage and redistribution
 * of this file, and for a DISCLAIMER OF ALL WARRANTIES.
 */

#include "tkInt.h"
#include "tkUnixInt.h"
#include "tkGlfwInt.h"
#include <GLFW/glfw3.h>
#include <GLFW/glfw3native.h>
#include <string.h>
#include <ctype.h>
#include <sys/mman.h>
#include <unistd.h>
#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <limits.h>
#include <systemd/sd-bus.h>
#include <xkbcommon/xkbcommon.h>
#include <xkbcommon/xkbcommon-compose.h>
#include <X11/keysymdef.h>

int TkWaylandIbus_Init(Tcl_Interp *interp);
void RemoveIbusContext(Tk_Window tkwin);

/*
 * Keyboard implementation.
 *
 * These functions implement XKB keyboard support for key translation for Tk on
 * Wayland.
 */

/*
 * Synthetic keycode range for IME‑generated Unicode characters.
 * The high bit (0x80000000) is not used by real X11 keycodes, so we
 * can safely encode any Unicode scalar value in the low 21 bits.
 */
#define SYNTHETIC_KEYCODE_BASE 0xFF000000
#define SYNTHETIC_KEYCODE(ch)  (SYNTHETIC_KEYCODE_BASE | (ch))

TkXKBState xkbState = {NULL, NULL, NULL, NULL, NULL, 0, 0, 0, 0};

/*
 * ----------------------------------------------------------------------------
 * TkpGetString --
 *
 *         Called in tkBind.c to generate a value for the %A field in a Tk
 *         <Key> event.  The stored text is consumed once: a second call for
 *         the same event returns an empty string.  This is intentional and
 *         matches the X11 pattern where XLookupString is called at most once
 *         per event.
 *
 * Results:
 *         Returns a string.
 *
 * Side effects:
 *         Clears the stored text after reading it.
 * ----------------------------------------------------------------------------
 */

const char*
TkpGetString(
    TkWindow *winPtr,
    TCL_UNUSED(XEvent*), /* eventPtr*/
    Tcl_DString *dsPtr)
{
    const char* result;
    TkWindow *toplevel = winPtr;

    while (!Tk_IsTopLevel(toplevel)) {
        toplevel = (TkWindow *) Tk_Parent(toplevel);
    }
    Tcl_DStringInit(dsPtr);
    result = Tcl_DStringAppend(dsPtr, TkWaylandGetStoredText(toplevel),
                               TCL_INDEX_NONE);
    TkWaylandClearStoredText(toplevel);
    return result;
}

/*
 * ----------------------------------------------------------------------------
 * TkpGetKeySym --
 *
 *         Called in tkBind.c to generate a value for the %K field in a Tk
 *         <Key> event.
 *
 * Results:
 *         Returns a keysym.
 *
 * Side effects:
 *         None.
 * ----------------------------------------------------------------------------
 */

KeySym
TkpGetKeySym(
    TCL_UNUSED(TkDisplay*), /*dispPtr */
    XEvent *eventPtr)           /* Description of X event. */
{
    return TkWaylandGetKeysymFromScancode(eventPtr->xkey.keycode);
}

/*
 * ----------------------------------------------------------------------------
 * TkpInitKeymapInfo --
 *
 *         This procedure is invoked to scan keymap information to recompute
 *         values that are important for binding, such as determining which
 *         modifier is associated with "mode switch".
 *
 * Results:
 *         None.
 *
 * Side effects:
 *         Keymap-related information in dispPtr is updated.
 * ----------------------------------------------------------------------------
 */

void
TkpInitKeymapInfo(TkDisplay *dispPtr)
{
    /*
     * Set up default modifier masks for Wayland/GLFW.  These correspond to the
     * standard X11 modifier assignments.
     */
    dispPtr->modeModMask = Mod5Mask;   /* AltGr / Mode_switch */
    dispPtr->altModMask  = Mod1Mask;   /* Alt */
    dispPtr->metaModMask = Mod4Mask;   /* Super/Windows key */

    /*
     * Lock modifiers are platform-independent.
     */
    dispPtr->lockUsage = LU_CAPS;
}

/*
 * ----------------------------------------------------------------------------
 * TkWaylandGetKeysymFromScancode --
 *
 *         Convert a keyboard scancode (evdev code) into an X11 keysym using
 *         the current XKB state.  If the scancode is a synthetic IME keycode,
 *         the Unicode keysym is extracted directly.
 *
 * Results:
 *         Returns the keysym, or NoSymbol if no XKB state is available.
 *
 * Side effects:
 *         None.
 * ----------------------------------------------------------------------------
 */

KeySym
TkWaylandGetKeysymFromScancode(
    int scancode)
{
    /* Synthetic keycode generated by IME commit/preedit. */
    if (scancode >= SYNTHETIC_KEYCODE_BASE) {
        return (KeySym)(scancode - SYNTHETIC_KEYCODE_BASE);
    }

    if (xkbState.state) {
        /*
         * The scancode is a kernel ev_code, but xkbcommon expects an X11
         * keycode, which is the scancode offset by 8.
         */
        return (KeySym) xkb_state_key_get_one_sym(xkbState.state,
                                                  scancode + 8);
    } else {
        return NoSymbol;
    }
}

/*
 * -----------------------------------------------------------------------------
 * TkpSetKeycodeAndState --
 *
 *         Given a keysym and an XEvent, set the keycode and modifier state
 *         fields of the event.  This is used by the [event generate] command.
 *
 *         The function scans the live XKB keymap to find a keycode that
 *         generates the given keysym.  If the keymap is not yet loaded, it
 *         falls back to a hard-coded table of common non-printable keys.
 *
 *         Level-to-modifier mapping:
 *           level 0  → no modifier
 *           level 1  → ShiftMask
 *           level ≥ 2 → Mod5Mask (AltGr)
 *
 * Results:
 *         None.
 *
 * Side effects:
 *         Modifies eventPtr->xkey.keycode and eventPtr->xkey.state.
 * ----------------------------------------------------------------------------
 */

void
TkpSetKeycodeAndState(
    TCL_UNUSED(Tk_Window),
    KeySym keysym,
    XEvent *eventPtr)
{

    if (xkbState.keymap) {
        xkb_keycode_t min_kc = xkb_keymap_min_keycode(xkbState.keymap);
        xkb_keycode_t max_kc = xkb_keymap_max_keycode(xkbState.keymap);
        xkb_keycode_t kc;

        for (kc = min_kc; kc <= max_kc; kc++) {
            xkb_layout_index_t num_layouts =
                xkb_keymap_num_layouts_for_key(xkbState.keymap, kc);
            xkb_layout_index_t layout;

            for (layout = 0; layout < num_layouts; layout++) {
                xkb_level_index_t num_levels =
                    xkb_keymap_num_levels_for_key(xkbState.keymap, kc, layout);
                xkb_level_index_t level;

                for (level = 0; level < num_levels; level++) {
                    const xkb_keysym_t *syms;
                    int n, i;

                    n = xkb_keymap_key_get_syms_by_level(
                            xkbState.keymap, kc, layout, level, &syms);

                    for (i = 0; i < n; i++) {
                        if (syms[i] == (xkb_keysym_t)keysym) {
                            /*
                             * kc is an XKB/X11 keycode (evdev + 8).
                             * Map the shift level to modifier bits:
                             *   level 0 → no modifier
                             *   level 1 → ShiftMask
                             *   level ≥ 2 → Mod5Mask (AltGr)
                             */
                            eventPtr->xkey.keycode = kc;
                            if (level == 1) {
                                eventPtr->xkey.state |= ShiftMask;
                            } else if (level >= 2) {
                                eventPtr->xkey.state |= Mod5Mask;
                            }
                            return;
                        }
                    }
                }
            }
        }
    }

    /*
     * Fallback for common keys when the XKB keymap is not yet loaded.  These
     * are X11 keycodes (evdev + 8) for a standard US-QWERTY layout.
     */
    switch (keysym) {
    case XK_Return:    eventPtr->xkey.keycode = 36;  break;
    case XK_Escape:    eventPtr->xkey.keycode = 9;   break;
    case XK_BackSpace: eventPtr->xkey.keycode = 22;  break;
    case XK_Tab:       eventPtr->xkey.keycode = 23;  break;
    case XK_space:     eventPtr->xkey.keycode = 65;  break;
    case XK_Left:      eventPtr->xkey.keycode = 113; break;
    case XK_Right:     eventPtr->xkey.keycode = 114; break;
    case XK_Up:        eventPtr->xkey.keycode = 111; break;
    case XK_Down:      eventPtr->xkey.keycode = 116; break;
    case XK_Home:      eventPtr->xkey.keycode = 110; break;
    case XK_End:       eventPtr->xkey.keycode = 115; break;
    case XK_Delete:    eventPtr->xkey.keycode = 119; break;
    case XK_Insert:    eventPtr->xkey.keycode = 118; break;
    default:
        /* Last resort: encode the low byte of the keysym. */
        eventPtr->xkey.keycode = keysym & 0xFFu;
        break;
    }
}

/*
 *----------------------------------------------------------------------
 *
 * XStringToKeysym --
 *
 *	Converts a human-readable keysym string name (e.g., "Right", "Return")
 *	into its corresponding X11/XKB KeySym numeric identifier.
 *
 * Results:
 *	The resolved KeySym value, or NoSymbol (0) if the string name is
 *	unrecognized or cannot be matched.
 *
 * Side effects:
 *	None.
 *
 *----------------------------------------------------------------------
 */

KeySym
XStringToKeysym(_Xconst char *string)
{
    if (string == NULL || *string == '\0') {
        return NoSymbol;
    }

    /*
     * Use xkbcommon's native utility to look up the keysym from its name string.
     * XKB_KEYSYM_NO_FLAGS ensures a strict, standard lookup matching standard names.
     */
    xkb_keysym_t sym = xkb_keysym_from_name(string, XKB_KEYSYM_NO_FLAGS);

    if (sym == XKB_KEYCODE_INVALID) {
        /*
         * Fallback check: If the case-sensitive exact lookup fails, some legacy
         * Tk scripts capitalize keysyms loosely. We can explicitly catch "Right"
         * if needed, but xkb_keysym_from_name is generally fully compliant with
         * standard X11 keysym string specifications.
         */
        return NoSymbol;
    }

    return (KeySym) sym;
}

/*
 * ----------------------------------------------------------------------------
 * XKeysymToString --
 *
 *         Convert a KeySym value to its string name.
 *
 *         NOTE: This stub is only correct when REDO_KEYSYM_LOOKUP is defined
 *         in the build.  See comment in XStringToKeysym above.
 *
 * Results:
 *         Always returns NULL.
 *
 * Side effects:
 *         None.
 * ----------------------------------------------------------------------------
 */

char *
XKeysymToString(KeySym keysym)
{
    return NULL;
}

/*
 * ----------------------------------------------------------------------------
 * InitializeXKB --
 *
 *         Initialize the XKB context, keymap, compose table, and state.
 *
 * Results:
 *         Returns 1 on success, 0 on failure.
 *
 * Side effects:
 *         Allocates global XKB resources.
 * ----------------------------------------------------------------------------
 */

static bool
InitializeXKB(void)
{
    const char *locale;

    /* Create an XKB context. */
    xkbState.context = xkb_context_new(XKB_CONTEXT_NO_FLAGS);
    if (!xkbState.context) {
        return false;
    }

    /* Obtain the locale for compose sequences. */
    locale = getenv("LC_ALL");
    if (!locale) locale = getenv("LC_CTYPE");
    if (!locale) locale = getenv("LANG");
    if (!locale) locale = "C";

    /* Create a compose table. */
    xkbState.compose_table = xkb_compose_table_new_from_locale(
            xkbState.context, locale, XKB_COMPOSE_COMPILE_NO_FLAGS);

    if (xkbState.compose_table) {
        xkbState.compose_state = xkb_compose_state_new(
                xkbState.compose_table, XKB_COMPOSE_STATE_NO_FLAGS);
    }

    /* Compile a keymap (default US layout as a starting point). */
    struct xkb_rule_names names = {
        .rules = "evdev",
        .model = "pc105",
        .layout = "us",
        .variant = "",
        .options = ""
    };

    xkbState.keymap = xkb_keymap_new_from_names(xkbState.context,
                          &names, XKB_KEYMAP_COMPILE_NO_FLAGS);
    if (!xkbState.keymap) {
        return false;
    }

    /* Create the XKB state object. */
    xkbState.state = xkb_state_new(xkbState.keymap);
    if (!xkbState.state) {
        return false;
    }

    return true;
}

/*
 * ----------------------------------------------------------------------------
 * CleanupXKB --
 *
 *         Free all XKB resources.
 *
 * Results:
 *         None.
 *
 * Side effects:
 *         The global XKB state is reset to NULL.
 * ----------------------------------------------------------------------------
 */

static void
CleanupXKB(void)
{
    if (xkbState.compose_state) {
        xkb_compose_state_unref(xkbState.compose_state);
        xkbState.compose_state = NULL;
    }
    if (xkbState.compose_table) {
        xkb_compose_table_unref(xkbState.compose_table);
        xkbState.compose_table = NULL;
    }
    if (xkbState.state) {
        xkb_state_unref(xkbState.state);
        xkbState.state = NULL;
    }
    if (xkbState.keymap) {
        xkb_keymap_unref(xkbState.keymap);
        xkbState.keymap = NULL;
    }
    if (xkbState.context) {
        xkb_context_unref(xkbState.context);
        xkbState.context = NULL;
    }
}

/*
 * ----------------------------------------------------------------------------
 * TkWaylandKeyInit --
 *
 *         Initialize the Wayland keyboard subsystem, including XKB and IME
 *         (IBus) integration.
 *
 *         IBus initialization is treated as optional: if the IBus daemon is
 *         not running (common for non-CJK users), the keyboard still functions
 *         correctly via XKB alone.
 *
 * Results:
 *         Returns true on success, false on failure (XKB failure only).
 *
 * Side effects:
 *         Creates the XKB context and attempts to start the IBus D-Bus
 *         connection.
 * ----------------------------------------------------------------------------
 */

bool
TkWaylandKeyInit(void)
{
    if (!InitializeXKB()) {
        fprintf(stderr, "TkWaylandKeyInit: failed to initialize xkb.\n");
        return false;
    }
    TkMainInfo *info = TkGetMainInfoList();
    /* IBus failure is non-fatal; keyboard works without it. */
    TkWaylandIbus_Init(info->interp);
    return true;
}

/*
 * ----------------------------------------------------------------------------
 * TkWaylandKeyCleanup --
 *
 *         Clean up all Wayland keyboard resources, including XKB.
 *
 * Results:
 *         None.
 *
 * Side effects:
 *         Frees the XKB state, keymap, and context.
 * ----------------------------------------------------------------------------
 */

void
TkWaylandKeyCleanup() {
    CleanupXKB();
}

/*
 * Input Method Editor implementation.
 *
 * This implementation is necessary because GLFW does not provide any built-in
 * support for IME despite requests dating back many years.  We use sd-bus to
 * connect to the IBus IME daemon.  IBus was chosen because it is widely used,
 * and the other primary IME library, Fcitx, provides a compatibility interface
 * for IBus.  IBus provides the UI (candidate windows, preëdit) and creates a
 * context for each Tk toplevel, then forwards committed text to the focused
 * text widget via a Tcl command.
 *
 * We use the direct D-Bus connection rather than the Wayland text-input
 * protocols because those would require managing a separate Wayland surface
 * with GLFW, which is complex and fragile.  GLFW does not expose any way to
 * hook directly into its Wayland surface.
 *
 * IBus D-Bus signal signatures (real wire format):
 *
 *   CommitText        (v)   – IBus.Text variant containing the committed string
 *   UpdatePreeditText (vub) – IBus.Text variant, uint32 cursor, bool visible
 *   HidePreeditText   ()    – hide the preedit (no arguments)
 *   ShowPreeditText   ()    – show the preedit (no arguments)
 *
 * Note: the signal is named "UpdatePreeditText" (not "UpdatePreedit").
 * Older documentation and some examples use the shorter name but modern
 * IBus engines (including Mozc and iBus-libpinyin) emit the full name.
 *
 * IBus.Text is a D-Bus struct: (sa{sv}sv) — (name, attachments, text,
 * attributes).  We unpack only the plain text string for simplicity.
 */


 /* IBus D-Bus constants. */

#define IBUS_SERVICE          "org.freedesktop.IBus"
#define IBUS_PATH             "/org/freedesktop/IBus"
#define IBUS_INTERFACE        "org.freedesktop.IBus"
#define IBUS_IC_INTERFACE     "org.freedesktop.IBus.InputContext"

/* IBus signal names. */
#define IBUS_SIGNAL_COMMIT_TEXT      "CommitText"
#define IBUS_SIGNAL_UPDATE_PREEDIT   "UpdatePreeditText"
#define IBUS_SIGNAL_HIDE_PREEDIT     "HidePreeditText"
#define IBUS_SIGNAL_SHOW_PREEDIT     "ShowPreeditText"

/* Bitmask identifiers defined by the IBus wire specification */
#define IBUS_CAP_PREEDIT_TEXT   (1u << 0)
#define IBUS_CAP_AUXILIARY_TEXT (1u << 1)
#define IBUS_CAP_LOOKUP_TABLE   (1u << 2)
#define IBUS_CAP_FOCUS          (1u << 3)


/* Per-window IBus context structure. */

typedef struct IbusContext {
    Tk_Window tkwin;            /* Tk toplevel this context belongs to. */
    Tk_Window focusedWidget;    /* Sub-widget currently holding keyboard focus.
                                 * Set by TkWaylandIbusFocusIn, cleared on
                                 * FocusOut.  Used by signal handlers instead
                                 * of dispPtr->focusPtr, which is unreliable on
                                 * Wayland. */
    char *obj_path;             /* D-Bus object path of the IBus input context. */
    sd_bus_slot *signal_slot;   /* Slot for CommitText signal subscription. */
    sd_bus_slot *preedit_slot;  /* Slot for UpdatePreeditText signal subscription. */
    sd_bus_slot *hide_slot;     /* Slot for HidePreeditText signal subscription. */
    sd_bus_slot *show_slot;     /* Slot for ShowPreeditText signal subscription. */
    Tcl_Interp *interp;         /* Tcl interpreter (for callbacks). */
    int enabled;                /* Whether IME is active for this window. */
    int composing;              /* Non-zero while IBus owns an active composition.
                                 * Set on UpdatePreeditText/ShowPreeditText,
                                 * cleared on CommitText/HidePreeditText.
                                 * Used by the GLFW char callback to suppress
                                 * raw latin input during IME composition. */
    int destroyed;              /* Set to 1 when the Tk window has been
                                 * destroyed; guards signal handlers against
                                 * using a stale tkwin pointer. */
    char *preeditText;          /* Current preedit/composing text (owned) */
    struct IbusContext *next;   /* Linked list pointer. */
} IbusContext;

/* Global IBus state. */
sd_bus *ibus_bus = NULL;
IbusContext *all_contexts = NULL;

/*
 * Re-entrancy guard for sd_bus_process.  Set to 1 while
 * IbusProcessKeyEvent is draining the bus synchronously so that
 * IbusBusHandler (the Tcl file handler) does not call sd_bus_process
 * concurrently on the same bus object.
 */
static int ibus_draining = 0;

/*
 * ----------------------------------------------------------------------------
 * FindContext --
 *
 *         Find the IBus context associated with a given Tk window.
 *
 * Results:
 *         Returns a pointer to the IbusContext structure, or NULL if no
 *         context exists for the window.
 *
 * Side effects:
 *         None.
 * ----------------------------------------------------------------------------
 */

static IbusContext *
FindContext(Tk_Window tkwin)
{
    IbusContext *ctx = all_contexts;
    while (ctx) {
        if (ctx->tkwin == tkwin)
            return ctx;
        ctx = ctx->next;
    }
    return NULL;
}
/*
 *----------------------------------------------------------------------
 *
 * IbusReadTextFromVariant --
 *
 * Helper to safely unpack an IBusText object wrapped inside a
 * D-Bus variant container. Dynamically inspects the signature to
 * handle protocol variations safely across different IBus versions.
 *
 * Results:
 * 0 on success, negative error code on failure.
 *
 * Side effects:
 * Moves message container cursor; sets text_out to point inside
 * the message buffer.
 *
 *----------------------------------------------------------------------
 */

static int
IbusReadTextFromVariant(
    sd_bus_message *m,
    const char **text_out)
{
    int r;
    char type;
    const char *contents = NULL;
    const char *objtype = NULL;

    *text_out = NULL;

    /* Expect a variant. */
    r = sd_bus_message_peek_type(m, &type, &contents);
    fprintf(stderr,
            "peek: r=%d type='%c' contents='%s'\n",
            r,
            type,
            contents ? contents : "(null)");

    if (r < 0) {
        return r;
    }

    if (type != SD_BUS_TYPE_VARIANT) {
        fprintf(stderr,
                "Expected VARIANT, got '%c'\n",
                type);
        return -EINVAL;
    }

    /* Enter variant. */
    r = sd_bus_message_enter_container(
            m,
            SD_BUS_TYPE_VARIANT,
            contents);
    fprintf(stderr,
            "enter variant -> r=%d\n",
            r);

    if (r < 0) {
        return r;
    }

    /* See what's actually inside. */
    r = sd_bus_message_peek_type(m, &type, &contents);
    fprintf(stderr,
            "inside variant: r=%d type='%c' contents='%s'\n",
            r,
            type,
            contents ? contents : "(null)");

    if (r < 0) {
        goto cleanup_variant;
    }

    if (type != SD_BUS_TYPE_STRUCT) {
        fprintf(stderr,
                "Expected STRUCT inside variant, got '%c'\n",
                type);
        r = -EINVAL;
        goto cleanup_variant;
    }

    /* Enter struct. */
    r = sd_bus_message_enter_container(
            m,
            SD_BUS_TYPE_STRUCT,
            NULL);
    fprintf(stderr,
            "enter struct -> r=%d\n",
            r);

    if (r < 0) {
        goto cleanup_variant;
    }

    /* First field should be "IBusText". */
    r = sd_bus_message_read(m, "s", &objtype);
    fprintf(stderr,
            "read object type -> r=%d value='%s'\n",
            r,
            objtype ? objtype : "(null)");

    if (r < 0) {
        goto cleanup_struct;
    }

    /* What comes next? */
    r = sd_bus_message_peek_type(m, &type, &contents);
    fprintf(stderr,
            "after object type: r=%d type='%c' contents='%s'\n",
            r,
            type,
            contents ? contents : "(null)");

    if (r < 0) {
        goto cleanup_struct;
    }

    /*
     * Old IBus encodings typically have an a{sv}
     * attributes dictionary here.
     */
    if (type == SD_BUS_TYPE_ARRAY) {
        fprintf(stderr,
                "skipping array '%s'\n",
                contents ? contents : "(null)");

        r = sd_bus_message_skip(m, "a{sv}");
        fprintf(stderr,
                "skip array -> r=%d\n",
                r);

        if (r < 0) {
            goto cleanup_struct;
        }
    }

    /* See what field follows. */
    r = sd_bus_message_peek_type(m, &type, &contents);
    fprintf(stderr,
            "before text read: r=%d type='%c' contents='%s'\n",
            r,
            type,
            contents ? contents : "(null)");

    if (r < 0) {
        goto cleanup_struct;
    }

    /* Try to read UTF-8 text. */
    r = sd_bus_message_read(m, "s", text_out);
    fprintf(stderr,
            "read text -> r=%d text='%s'\n",
            r,
            (r >= 0 && *text_out) ? *text_out : "(null)");

cleanup_struct:
    sd_bus_message_exit_container(m);

cleanup_variant:
    sd_bus_message_exit_container(m);

    return r;
}

/*
 * ----------------------------------------------------------------------------
 * TkWaylandSendUnicodeString --
 *
 *         Generate synthetic KeyPress events for committed or preedit text.
 *         Builds a complete XEvent.
 *
 * Results:
 *         None.
 *
 * Side effects:
 *         Queues KeyPress events to the correct widget.
 * ----------------------------------------------------------------------------
 */

static void
TkWaylandSendUnicodeString(
    Tk_Window tkwin,
    const char *utf8_str)
{
    if (!utf8_str || !*utf8_str || !tkwin) {
        return;
    }

    /*
     * Stored text lives on the toplevel's privatePtr->pendingText and is
     * read by TkpGetString to populate %A in tkBind.c.  Walk up to find
     * the toplevel so we can set it before queuing the synthetic KeyPress.
     */
    TkWindow *topPtr = (TkWindow *)tkwin;
    while (topPtr && !Tk_IsTopLevel(topPtr)) {
        topPtr = (TkWindow *)Tk_Parent(topPtr);
    }
    if (!topPtr) return;

    Display *display = Tk_Display(tkwin);
    Window window = Tk_WindowId(tkwin);

    Tcl_Time now;
    Tcl_GetTime(&now);
    Time time = (Time)(now.sec * 1000 + now.usec / 1000);

    XEvent xEvent;
    memset(&xEvent, 0, sizeof(XEvent));

    xEvent.xany.display = display;
    xEvent.xany.window  = window;
    xEvent.xany.type    = KeyPress;

    xEvent.xkey.root        = XRootWindow(display, 0);
    xEvent.xkey.time        = time;
    xEvent.xkey.same_screen = True;
    xEvent.xkey.state       = 0;

    /* Add current modifiers from XKB if available. */
    if (xkbState.state && xkbState.keymap) {
        xkb_mod_mask_t mods = xkb_state_serialize_mods(xkbState.state,
                                XKB_STATE_MODS_DEPRESSED | XKB_STATE_MODS_LATCHED);
        if (mods & (1 << xkb_keymap_mod_get_index(xkbState.keymap, "Shift")))
            xEvent.xkey.state |= ShiftMask;
        if (mods & (1 << xkb_keymap_mod_get_index(xkbState.keymap, "Control")))
            xEvent.xkey.state |= ControlMask;
        if (mods & (1 << xkb_keymap_mod_get_index(xkbState.keymap, "Alt")))
            xEvent.xkey.state |= Mod1Mask;
        if (mods & (1 << xkb_keymap_mod_get_index(xkbState.keymap, "Mod5")))
            xEvent.xkey.state |= Mod5Mask;
    }

    /*
     * Store the entire committed string once and send a single synthetic
     * KeyPress to deliver it.  TkpGetString reads and clears pendingText
     * on the first call, so per-character queuing loses all characters
     * after the first.  A single event carrying the full string avoids
     * that: the widget's <<Key>> binding calls TkpGetString once and gets
     * the complete UTF-8 string.
     *
     * Codepoint 0 is used as the routing token — it is in the synthetic
     * range and will never match a real key binding.
     */
    TkWaylandSetStoredText(topPtr, utf8_str);
    xEvent.xkey.keycode = SYNTHETIC_KEYCODE(0);
    Tk_QueueWindowEvent(&xEvent, TCL_QUEUE_TAIL);
}

/*
 * ----------------------------------------------------------------------------
 * OnCommitText --
 *
 *	    D-Bus signal handler for the IBus "CommitText" signal. Called when
 *	    the IME has finished composing a text string and it should be
 *	    inserted into the focused widget.
 *
 *	    Wire signature: CommitText(v) where v contains an IBus.Text struct.
 *
 * Results:
 *	    Returns 0 on success, or a negative error code on failure.
 *
 * Side effects:
 *	    Queues key events and virtual events for the target sub-widget.
 * ----------------------------------------------------------------------------
 */

static int
OnCommitText(
    sd_bus_message *m,
    void *userdata,
    sd_bus_error *ret_error)
{
    IbusContext *ctx = (IbusContext *)userdata;
    const char *text = NULL;
    int r;

    fprintf(stderr, ">>> OnCommitText\n");

    /*
     * Guard against signals that arrive after the Tk window has been
     * destroyed.  RemoveIbusContext sets this flag before freeing, but
     * in-flight D-Bus messages may still call back here.
     */
    if (!ctx || ctx->destroyed) {
        return 0;
    }

    r = IbusReadTextFromVariant(m, &text);
    if (r < 0 || !text) {
        return 0;
    }

    /*
     * Use the focused sub-widget recorded at FocusIn time.  Do NOT
     * dereference dispPtr->focusPtr here: on Wayland that pointer is not
     * reliably kept in sync and may be stale, causing "not found in
     * dictionary" errors and segfaults.
     */
    Tk_Window focusWin = ctx->focusedWidget ? ctx->focusedWidget : ctx->tkwin;

    /* Clear any marked/preedit region before inserting committed text. */
    Tk_SendVirtualEvent(focusWin, "TkClearIMEMarkedText", NULL);

    if (*text) {
        TkWaylandSendUnicodeString(focusWin, text);
    }

    /* Composition is complete — clear preedit state and composing flag. */
    if (ctx->preeditText) {
        free(ctx->preeditText);
        ctx->preeditText = NULL;
    }
    ctx->composing = 0;

    return 0;
}
/*
 * ----------------------------------------------------------------------------
 * OnUpdatePreedit --
 *
 *         D-Bus signal handler for the IBus "UpdatePreeditText" signal.
 *         Called when the IME preëdit string (the ongoing composition) changes.
 *
 *         Wire signature: UpdatePreeditText(v, u, b)
 *           v – IBus.Text variant (the preëdit string)
 *           u – uint32 cursor position within the preëdit
 *           b – bool visible
 *
 *         The preëdit is displayed using the standard Tk virtual events:
 *           <<TkStartIMEMarkedText>>, <<TkEndIMEMarkedText>>, and
 *           <<TkClearIMEMarkedText>>.  The preëdit text itself is inserted
 *         as synthetic key events (just like committed text) but between the
 *         start and end markers, causing the Tk bindings to underline or
 *         select the marked region.
 *
 * Results:
 *         Returns 0 on success, or a negative error code on failure.
 *
 * Side effects:
 *         Sends virtual events and synthetic key events.
 *         Sets ctx->composing = 1 while composition is active.
 * ----------------------------------------------------------------------------
 */

static int
OnUpdatePreedit(
    sd_bus_message *m,
    void *userdata,
    sd_bus_error *ret_error)
{
    IbusContext *ctx = (IbusContext *)userdata;
    const char *text = NULL;
    uint32_t cursor_pos = 0;
    int32_t visible = 0;
    int r;

    fprintf(stderr, ">>> OnUpdatePreedit\n");

    /* Guard against post-destruction callbacks (see OnCommitText). */
    if (!ctx || ctx->destroyed) {
        return 0;
    }

    r = IbusReadTextFromVariant(m, &text);
    if (r < 0) {
        return 0;
    }

    r = sd_bus_message_read(m, "ub", &cursor_pos, &visible);
    if (r < 0) {
        return 0;
    }

    /*
     * Use the widget recorded at FocusIn time, not dispPtr->focusPtr.
     * See OnCommitText for rationale.
     */
    Tk_Window focusWin = ctx->focusedWidget ? ctx->focusedWidget : ctx->tkwin;

    /* Always clear previous marked region first. */
    Tk_SendVirtualEvent(focusWin, "TkClearIMEMarkedText", NULL);

    if (!visible || !text || !*text) {
        if (ctx->preeditText) {
            free(ctx->preeditText);
            ctx->preeditText = NULL;
        }
        ctx->composing = 0;
        return 0;
    }

    /* Update stored preedit text and mark composition as active. */
    if (ctx->preeditText) {
        free(ctx->preeditText);
    }
    ctx->preeditText = strdup(text);
    ctx->composing = 1;

    /* Show new preedit. */
    Tk_SendVirtualEvent(focusWin, "TkStartIMEMarkedText", NULL);
    TkWaylandSendUnicodeString(focusWin, text);
    Tk_SendVirtualEvent(focusWin, "TkEndIMEMarkedText", NULL);

    return 0;
}

/*
 * ----------------------------------------------------------------------------
 * OnHidePreeditText --
 *
 *         D-Bus signal handler for the IBus "HidePreeditText" signal.
 *         Called when the IME wants the preëdit to be hidden (e.g., after
 *         committing or cancelling composition).
 *
 *         Wire signature: HidePreeditText()  — no arguments.
 *
 * Results:
 *         Returns 0.
 *
 * Side effects:
 *         Sends TkClearIMEMarkedText virtual event and clears composing state.
 * ----------------------------------------------------------------------------
 */

static int
OnHidePreeditText(
    sd_bus_message *m,
    void *userdata,
    sd_bus_error *ret_error)
{
    IbusContext *ctx = (IbusContext *)userdata;

    fprintf(stderr, ">>> OnHidePreeditText\n");

    if (!ctx || ctx->destroyed) {
        return 0;
    }

    Tk_Window focusWin = ctx->focusedWidget ? ctx->focusedWidget : ctx->tkwin;
    Tk_SendVirtualEvent(focusWin, "TkClearIMEMarkedText", NULL);

    if (ctx->preeditText) {
        free(ctx->preeditText);
        ctx->preeditText = NULL;
    }
    ctx->composing = 0;

    return 0;
}

/*
 * ----------------------------------------------------------------------------
 * OnShowPreeditText --
 *
 *         D-Bus signal handler for the IBus "ShowPreeditText" signal.
 *         Called when the IME wants the preëdit to be shown.  The actual
 *         text arrives via a subsequent UpdatePreeditText signal; this
 *         signal is informational.  We only set the composing flag here so
 *         that the GLFW char callback suppresses raw input immediately.
 *
 *         Wire signature: ShowPreeditText()  — no arguments.
 *
 * Results:
 *         Returns 0.
 *
 * Side effects:
 *         Sets ctx->composing = 1.
 * ----------------------------------------------------------------------------
 */

static int
OnShowPreeditText(
    sd_bus_message *m,
    void *userdata,
    sd_bus_error *ret_error)
{
    IbusContext *ctx = (IbusContext *)userdata;

    fprintf(stderr, ">>> OnShowPreeditText\n");

    if (!ctx || ctx->destroyed) {
        return 0;
    }

    ctx->composing = 1;
    return 0;
}

/*
 * ----------------------------------------------------------------------------
 * FreeIbusContext --
 *
 *         Free all resources owned by an IbusContext.  Does not unlink it
 *         from the global list.
 *
 * Results:
 *         None.
 *
 * Side effects:
 *         Unregisters signal slots and frees memory.
 * ----------------------------------------------------------------------------
 */

static void
FreeIbusContext(IbusContext *ctx)
{
    if (!ctx) return;

    if (ctx->preeditText) {
        free(ctx->preeditText);
        ctx->preeditText = NULL;
    }
    if (ctx->show_slot) {
        sd_bus_slot_unref(ctx->show_slot);
        ctx->show_slot = NULL;
    }
    if (ctx->hide_slot) {
        sd_bus_slot_unref(ctx->hide_slot);
        ctx->hide_slot = NULL;
    }
    if (ctx->preedit_slot) {
        sd_bus_slot_unref(ctx->preedit_slot);
        ctx->preedit_slot = NULL;
    }
    if (ctx->signal_slot) {
        sd_bus_slot_unref(ctx->signal_slot);
        ctx->signal_slot = NULL;
    }
    if (ctx->obj_path) {
        free(ctx->obj_path);
        ctx->obj_path = NULL;
    }
    Tcl_Free(ctx);
}

/*
 * ----------------------------------------------------------------------------
 * RemoveIbusContext --
 *
 *         Remove a context from the global list and free it.
 *         Called on window destruction.
 *
 * Results:
 *         None.
 *
 * Side effects:
 *         None.
 * ----------------------------------------------------------------------------
 */

void
RemoveIbusContext(Tk_Window tkwin)
{
    IbusContext *ctx = all_contexts;
    IbusContext **prev = &all_contexts;

    while (ctx) {
        if (ctx->tkwin == tkwin) {
            *prev = ctx->next;

            /*
             * Mark the context destroyed before draining.  Any signals that
             * fire during the drain will see the flag and return immediately
             * without touching tkwin or focusedWidget.
             */
            ctx->destroyed = 1;
            ctx->focusedWidget = NULL;

            /*
             * Drain any signals already queued on the D-Bus file descriptor
             * so that their handlers run while ctx is still allocated.  This
             * prevents a use-after-free when a CommitText or UpdatePreedit
             * signal was buffered just before the window closed.
             */
            if (ibus_bus) {
                int n;
                do { n = sd_bus_process(ibus_bus, NULL); } while (n > 0);
            }

            FreeIbusContext(ctx);
            return;
        }
        prev = &ctx->next;
        ctx = ctx->next;
    }
}

/*
 * ----------------------------------------------------------------------------
 * IbusFocusIn --
 *
 *         Inform IBus that a toplevel window (or a widget inside it) has
 *         received keyboard focus.
 *
 * Results:
 *         None.
 *
 * Side effects:
 *         Sends a FocusIn D-Bus call to the IBus input context.
 * ----------------------------------------------------------------------------
 */

static void IbusFocusIn(IbusContext *ctx)
{
    if (!ctx || !ibus_bus || !ctx->obj_path) return;
    sd_bus_error error = SD_BUS_ERROR_NULL;
    sd_bus_call_method(ibus_bus,
                       IBUS_SERVICE,
                       ctx->obj_path,
                       IBUS_IC_INTERFACE,
                       "FocusIn",
                       &error,
                       NULL,
                       "");
    sd_bus_error_free(&error);
}

/*
 * ----------------------------------------------------------------------------
 * IbusFocusOut --
 *
 *         Inform IBus that a toplevel window has lost keyboard focus.
 *
 * Results:
 *         None.
 *
 * Side effects:
 *         Sends a FocusOut D-Bus call to the IBus input context.
 * ----------------------------------------------------------------------------
 */

static void IbusFocusOut(IbusContext *ctx)
{
    if (!ctx || !ibus_bus || !ctx->obj_path) return;
    sd_bus_error error = SD_BUS_ERROR_NULL;
    sd_bus_call_method(ibus_bus,
                       IBUS_SERVICE,
                       ctx->obj_path,
                       IBUS_IC_INTERFACE,
                       "FocusOut",
                       &error,
                       NULL,
                       "");
    sd_bus_error_free(&error);
}

/*
 * ----------------------------------------------------------------------------
 * IbusEnable --
 *
 *         Enable the IME for a given IBus context.
 *
 * Results:
 *         None.
 *
 * Side effects:
 *         Sends an Enable D-Bus call and sets the context's enabled flag.
 * ----------------------------------------------------------------------------
 */

static void IbusEnable(IbusContext *ctx)
{
    if (!ctx || !ibus_bus || !ctx->obj_path) return;
    if (ctx->enabled) return;
    sd_bus_error error = SD_BUS_ERROR_NULL;
    sd_bus_call_method(ibus_bus,
                       IBUS_SERVICE,
                       ctx->obj_path,
                       IBUS_IC_INTERFACE,
                       "Enable",
                       &error,
                       NULL,
                       "");
    sd_bus_error_free(&error);
    ctx->enabled = 1;
}

/*
 * ----------------------------------------------------------------------------
 * IbusDisable --
 *
 *         Disable the IME for a given IBus context.
 *
 * Results:
 *         None.
 *
 * Side effects:
 *         Sends a Disable D-Bus call and clears the context's enabled flag.
 * ----------------------------------------------------------------------------
 */

static void IbusDisable(IbusContext *ctx)
{
    if (!ctx || !ibus_bus || !ctx->obj_path) return;
    if (!ctx->enabled) return;
    sd_bus_error error = SD_BUS_ERROR_NULL;
    sd_bus_call_method(ibus_bus,
                       IBUS_SERVICE,
                       ctx->obj_path,
                       IBUS_IC_INTERFACE,
                       "Disable",
                       &error,
                       NULL,
                       "");
    sd_bus_error_free(&error);
    ctx->enabled = 0;
}

/*
 * ----------------------------------------------------------------------------
 * IbusProcessKeyEvent --
 *
 *         Send a key event to the IBus daemon for processing.  If the IME
 *         handles the event (e.g., starts composition), the application should
 *         not process the key further.
 *
 * Results:
 *         Returns 1 if IBus handled the key event, 0 otherwise.
 *
 * Side effects:
 *         May change the internal state of the IBus input context.
 * ----------------------------------------------------------------------------
 */

static int IbusProcessKeyEvent(
                   IbusContext *ctx,
                   uint32_t keyval,
                   uint32_t keycode,
                   uint32_t state)
{
    if (!ctx || !ibus_bus || !ctx->obj_path) return 0;

    fprintf(stderr, "IbusProcessKeyEvent (Async): sending keyval=0x%04x keycode=%u state=0x%x\n",
            keyval, keycode, state);

    int r;

    sd_bus_error error = SD_BUS_ERROR_NULL;
    sd_bus_message *reply = NULL;
    int handled = 0;

    r = sd_bus_call_method(ibus_bus,
                           IBUS_SERVICE,
                           ctx->obj_path,
                           IBUS_IC_INTERFACE,
                           "ProcessKeyEvent",
                           &error,
                           &reply,
                           "uuu",
                           keyval, keycode, state);
    if (r < 0) {
        fprintf(stderr, "    ProcessKeyEvent failed: %s\n",
                error.message ? error.message : strerror(-r));
        sd_bus_error_free(&error);
        return 0;
    }

    sd_bus_message_read(reply, "b", &handled);
    sd_bus_message_unref(reply);
    sd_bus_error_free(&error);

    fprintf(stderr, "    IBus returned handled = %d\n", handled);

    /*
     * Drain any CommitText/UpdatePreedit signals IBus queued in response.
     *
     * Re-entrancy guard: the Tcl file handler (IbusBusHandler) may be
     * scheduled concurrently.  If it fires while we are draining here it
     * would call sd_bus_process again on the same bus, which is not safe.
     * The file-scope ibus_draining flag prevents that: IbusBusHandler
     * checks it and returns immediately when set.
     */
    if (!ibus_draining) {
        ibus_draining = 1;
        int n;
        do { n = sd_bus_process(ibus_bus, NULL); } while (n > 0);
        ibus_draining = 0;
    }

    return handled;
}
/*
 * ---------------------------------------------------------------------
 * Tk_SetCaretPos --
 *
 *         Called by text widgets to report the screen position of the
 *         insertion cursor.  We store it in the standard TkCaret field on
 *         the display (so Tk internals stay consistent) and then forward
 *         the screen-absolute rectangle to IBus via SetCursorLocationRelative
 *         so the IME candidate window appears next to the caret.
 *
 *         On Wayland, glfwGetWindowPos is unsupported so the toplevel's true
 *         screen position is unknown.  SetCursorLocationRelative accepts
 *         coordinates relative to the window surface.
 *
 *         height is the line height at the caret; we pass zero width because
 *         the caret is a point, not a selection rectangle.
 *
 * Results:
 *         None.
 *
 * Side effects:
 *         Updates dispPtr->caret.  Sends a SetCursorLocationRelative D-Bus call to
 *         the IBus input context for the enclosing toplevel, if one exists.
 * ----------------------------------------------------------------------
 */


void
Tk_SetCaretPos(
    Tk_Window tkwin,
    int x,
    int y,
    int height)
{
    TkWindow *winPtr = (TkWindow *) tkwin;
    TkDisplay *dispPtr = winPtr->dispPtr;

    /* Mark widget as capable of text input. */
    winPtr->flags |= TK_CAN_INPUT_TEXT;

    /* Skip if nothing changed. */
    if ((dispPtr->caret.winPtr == winPtr)
            && (dispPtr->caret.x == x)
            && (dispPtr->caret.y == y)
            && (dispPtr->caret.height == height)) {
        return;
    }

    dispPtr->caret.winPtr = winPtr;
    dispPtr->caret.x      = x;
    dispPtr->caret.y      = y;
    dispPtr->caret.height = height;

    if (!ibus_bus) return;

    /* Find toplevel context. */
    TkWindow *topPtr = winPtr;
    while (topPtr && !Tk_IsTopLevel(topPtr)) {
        topPtr = (TkWindow *) Tk_Parent(topPtr);
    }
    if (!topPtr) return;

    IbusContext *ctx = FindContext((Tk_Window) topPtr);
    if (!ctx || !ctx->obj_path) return;

    /*
     * Compute the caret position relative to the GLFW/Wayland surface.
     *
     * Tk_GetRootCoords is not used here because on this backend it returns
     * 0,0 for child windows: child widgets share the toplevel's Wayland
     * surface and have no independent compositor position.  Instead we
     * accumulate the widget's position relative to the toplevel by walking
     * the parent chain, then add the caller-supplied intra-widget offset.
     *
     * The result is surface-relative, which is exactly what
     * SetCursorLocationRelative expects.
     */
    int relX = x;
    int relY = y;
    {
        TkWindow *w = winPtr;
        while (w && !Tk_IsTopLevel(w)) {
            relX += w->changes.x;
            relY += w->changes.y;
            w = (TkWindow *) Tk_Parent(w);
        }
    }

    sd_bus_error error = SD_BUS_ERROR_NULL;
    sd_bus_call_method(ibus_bus,
                       IBUS_SERVICE,
                       ctx->obj_path,
                       IBUS_IC_INTERFACE,
                       "SetCursorLocationRelative",
                       &error,
                       NULL,
                       "iiii",
                       (int32_t) relX,
                       (int32_t) relY,
                       (int32_t) 0,      /* width = 0 (caret) */
                       (int32_t) height);
    sd_bus_error_free(&error);
}

/*
 * ----------------------------------------------------------------------------
 * TkWaylandIbusCreateContext --
 *
 *          Called from GLFW callbacks when a new toplevel GLFWwindow is
 *          created (and on subsequent FocusIn if no context exists).
 *
 * Results:
 *         Returns TCL_OK on success, TCL_ERROR on failure.
 *
 * Side effects:
 *         Creates a new IBus input context, subscribes to signals,
 *         and adds it to the global linked list.
 * ----------------------------------------------------------------------------
 */

int
TkWaylandIbusCreateContext(
    Tcl_Interp *interp,
    Tk_Window   tkwin)
{
    sd_bus_error error = SD_BUS_ERROR_NULL;
    sd_bus_message *reply = NULL;
    int r;

    if (!ibus_bus) {
        return TCL_ERROR;
    }

    /* If context already exists, early exit. */
    if (FindContext(tkwin)) {
        fprintf(stderr, "CreateIbusContext: Context already exists for window %p\n", tkwin);
        return TCL_OK;
    }

    /* Request new input context from IBus daemon. */
    r = sd_bus_call_method(ibus_bus,
                           IBUS_SERVICE,
                           IBUS_PATH,
                           IBUS_INTERFACE,
                           "CreateInputContext",
                           &error,
                           &reply,
                           "s",
                           "TkWaylandApp");
    if (r < 0) {
        fprintf(stderr, "IBus: CreateInputContext failed: %s\n",
                error.message ? error.message : strerror(-r));
        sd_bus_error_free(&error);
        return TCL_ERROR;
    }

    const char *path_tmp = NULL;
    r = sd_bus_message_read(reply, "o", &path_tmp);
    if (r < 0 || !path_tmp) {
        fprintf(stderr, "IBus: Failed to read object path: %s\n", strerror(-r));
        sd_bus_message_unref(reply);
        sd_bus_error_free(&error);
        return TCL_ERROR;
    }

    fprintf(stderr, "IBus: Created remote input context -> %s\n", path_tmp);

    /* Allocate and initialize context. */
    IbusContext *ctx = (IbusContext *)Tcl_Alloc(sizeof(IbusContext));
    if (!ctx) {
        sd_bus_message_unref(reply);
        sd_bus_error_free(&error);
        return TCL_ERROR;
    }
    memset(ctx, 0, sizeof(IbusContext));

    ctx->tkwin = tkwin;
    ctx->focusedWidget = NULL;
    {
        TkWindow *topPtr = (TkWindow *)tkwin;
        TkWindow *focusPtr = topPtr->dispPtr ? topPtr->dispPtr->focusPtr : NULL;
        if (focusPtr && !Tk_IsTopLevel(focusPtr)) {
            ctx->focusedWidget = (Tk_Window)focusPtr;
        } else {
            ctx->focusedWidget = tkwin;
        }
    }
    ctx->obj_path = strdup(path_tmp);
    ctx->interp = interp;
    ctx->enabled = 0;
    ctx->destroyed = 0;

    if (!ctx->obj_path) {
        Tcl_Free(ctx);
        sd_bus_message_unref(reply);
        sd_bus_error_free(&error);
        return TCL_ERROR;
    }

    sd_bus_message_unref(reply);
    sd_bus_error_free(&error);

    /* Subscribe to signals. */
    {
        char rule[512];

        snprintf(rule, sizeof(rule),
                 "type='signal',path='%s',interface='%s',member='CommitText'",
                 ctx->obj_path, IBUS_IC_INTERFACE);
        r = sd_bus_add_match(ibus_bus, &ctx->signal_slot, rule, OnCommitText, ctx);
        if (r < 0) {
            fprintf(stderr, "Warning: CommitText subscription failed: %s\n", strerror(-r));
        }

        snprintf(rule, sizeof(rule),
                 "type='signal',path='%s',interface='%s',member='UpdatePreeditText'",
                 ctx->obj_path, IBUS_IC_INTERFACE);
        r = sd_bus_add_match(ibus_bus, &ctx->preedit_slot, rule, OnUpdatePreedit, ctx);
        if (r < 0) {
            fprintf(stderr, "Warning: UpdatePreeditText subscription failed: %s\n", strerror(-r));
        }

        snprintf(rule, sizeof(rule),
                 "type='signal',path='%s',interface='%s',member='HidePreeditText'",
                 ctx->obj_path, IBUS_IC_INTERFACE);
        r = sd_bus_add_match(ibus_bus, &ctx->hide_slot, rule, OnHidePreeditText, ctx);
        if (r < 0) {
            fprintf(stderr, "Warning: HidePreeditText subscription failed: %s\n", strerror(-r));
        }

        snprintf(rule, sizeof(rule),
                 "type='signal',path='%s',interface='%s',member='ShowPreeditText'",
                 ctx->obj_path, IBUS_IC_INTERFACE);
        r = sd_bus_add_match(ibus_bus, &ctx->show_slot, rule, OnShowPreeditText, ctx);
        if (r < 0) {
            fprintf(stderr, "Warning: ShowPreeditText subscription failed: %s\n", strerror(-r));
        }
    }

    /* Set capabilities. */
    uint32_t caps = IBUS_CAP_PREEDIT_TEXT | IBUS_CAP_FOCUS;
    r = sd_bus_call_method(ibus_bus,
                           IBUS_SERVICE,
                           ctx->obj_path,
                           IBUS_IC_INTERFACE,
                           "SetCapabilities",
                           NULL, NULL, "u", caps);
    if (r < 0) {
        fprintf(stderr, "IBus: SetCapabilities failed (non-fatal): %s\n", strerror(-r));
    }

    /* Insert into global linked list.  */
    ctx->next = all_contexts;
    all_contexts = ctx;

    /*
     * Mozc and other engines require FocusIn followed by Enable immediately
     * after context creation; without it they remain in Direct Input mode
     * for the lifetime of the context.  IbusEnable sets ctx->enabled = 1.
     */
    IbusFocusIn(ctx);
    IbusEnable(ctx);
    sd_bus_call_method(ibus_bus, IBUS_SERVICE, ctx->obj_path, IBUS_IC_INTERFACE,
                   "Reset", &error, NULL, "");

    fprintf(stderr, "CreateIbusContext: Successfully added context for window %p\n", tkwin);

    return TCL_OK;
}

/*
 * ----------------------------------------------------------------------------
 * CreateIbusContext --
 *
 *         Create an IBus input context for a given Tk toplevel window.
 *
 * Results:
 *         Returns TCL_OK on success, or TCL_ERROR on failure.  An error
 *         message is left in the interpreter.
 *
 * Side effects:
 *         Creates a new input context on the IBus daemon, subscribes to
 *         its signals, and adds the context to the global list.
 * ----------------------------------------------------------------------------
 */

static int CreateIbusContext(
			     Tcl_Interp *interp,
			     Tk_Window tkwin)
{
    /* Operations moved to TkWaylandIbusCreateContext. */
    return TkWaylandIbusCreateContext(interp, tkwin);
}


/*
 * ----------------------------------------------------------------------------
 * TkWaylandIbusFocusIn --
 *
 *         Public wrapper called from TkGlfwWindowFocusCallback when a window
 *         gains focus.  Looks up the IBus context for the toplevel and calls
 *         IbusFocusIn + IbusEnable so callers need not see IbusContext*.
 *
 * Results:
 *         None.
 *
 * Side effects:
 *         Sends FocusIn and Enable D-Bus calls to the IBus input context.
 * ----------------------------------------------------------------------------
 */

void
TkWaylandIbusFocusIn(
    Tk_Window tkwin)
{
    IbusContext *ctx = FindContext(GetToplevelOfWidget(tkwin));
    if (!ctx) return;

    /*
     * Record which sub-widget currently has keyboard focus so that
     * OnCommitText and OnUpdatePreedit can route events to it directly,
     * without trusting dispPtr->focusPtr (unreliable on Wayland).
     */
    ctx->focusedWidget = tkwin;

    IbusFocusIn(ctx);
    IbusEnable(ctx);
}

/*
 * ----------------------------------------------------------------------------
 * TkWaylandIbusFocusOut --
 *
 *         Public wrapper called from TkGlfwWindowFocusCallback when a window
 *         loses focus.  Looks up the IBus context and calls IbusFocusOut +
 *         IbusDisable.
 *
 * Results:
 *         None.
 *
 * Side effects:
 *         Sends FocusOut and Disable D-Bus calls to the IBus input context.
 * ----------------------------------------------------------------------------
 */

void
TkWaylandIbusFocusOut(Tk_Window tkwin)
{
    IbusContext *ctx = FindContext(GetToplevelOfWidget(tkwin));
    if (!ctx) return;

    /*
     * Use the widget we recorded at FocusIn time for the preedit cancel.
     * Fall back to the toplevel if no sub-widget was recorded.
     */
    Tk_Window focusWin = ctx->focusedWidget ? ctx->focusedWidget : ctx->tkwin;

    /* Cancel any ongoing composition. */
    if (ctx->preeditText) {
        Tk_SendVirtualEvent(focusWin, "TkClearIMEMarkedText", NULL);
        free(ctx->preeditText);
        ctx->preeditText = NULL;
    }

    /* Clear the recorded focus widget — no sub-widget has focus now. */
    ctx->focusedWidget = NULL;

    IbusFocusOut(ctx);
    IbusDisable(ctx);
}

/*
 * ----------------------------------------------------------------------------
 * TkWaylandIbusProcessKey -
 *
 *         Public wrapper called from TkGlfwKeyCallback.  Looks up the IBus
 *         context for the focused toplevel and forwards the key event to the
 *         IBus daemon.
 *
 * Results:
 *         Returns true if IBus consumed the key event (caller should suppress the
 *         normal Tk KeyPress event), false otherwise.
 *
 * Side effects:
 *         May start or advance IME composition.
 * ----------------------------------------------------------------------------
 */

bool
TkWaylandIbusProcessKey(
    Tk_Window tkwin,
    uint32_t  keyval,
    uint32_t  keycode,
    uint32_t  state)
{
    IbusContext *ctx = FindContext(GetToplevelOfWidget(tkwin));
    if (!ctx) return false;
    return IbusProcessKeyEvent(ctx, keyval, keycode, state) != 0;
}

/*
 * ----------------------------------------------------------------------------
 * CmdCreateContext --
 *
 *         Creates an IBus input context for the given toplevel window.
 *
 * Results:
 *         Returns TCL_OK on success, TCL_ERROR on failure.
 *
 * Side effects:
 *         Creates a new IBus context and stores it in the global list.
 * ----------------------------------------------------------------------------
 */

int CmdCreateContext(
		     ClientData clientData,
		     Tcl_Interp *interp,
		     int objc,
		     Tcl_Obj *const objv[])
{
    if (objc != 2) {
        Tcl_WrongNumArgs(interp, 1, objv, "window");
        return TCL_ERROR;
    }
    const char *winName = Tcl_GetString(objv[1]);
    Tk_Window tkwin = Tk_NameToWindow(interp, winName, Tk_MainWindow(interp));
    if (!tkwin) {
        Tcl_SetObjResult(interp, Tcl_NewStringObj("Invalid window name", -1));
        return TCL_ERROR;
    }
    if (!Tk_IsTopLevel(tkwin)) {
        Tcl_SetObjResult(interp, Tcl_NewStringObj("Not a toplevel window", -1));
        return TCL_ERROR;
    }
    return CreateIbusContext(interp, tkwin);
}

/*
 * ----------------------------------------------------------------------------
 * CmdFocusIn --
 *
 *         Informs IBus that a toplevel window  (or a widget inside it)
 *		   has gained focus, and enables the IME.
 *
 *
 * Results:
 *         Returns TCL_OK on success, TCL_ERROR on failure.
 *
 * Side effects:
 *         Sends FocusIn and Enable D-Bus calls to the IBus context.
 * ----------------------------------------------------------------------------
 */

static int CmdFocusIn(
		      ClientData clientData,
		      Tcl_Interp *interp,
                      int objc,
		      Tcl_Obj *const objv[])
{
    if (objc != 2) {
        Tcl_WrongNumArgs(interp, 1, objv, "window");
        return TCL_ERROR;
    }
    const char *winName = Tcl_GetString(objv[1]);
    Tk_Window tkwin = Tk_NameToWindow(interp, winName, Tk_MainWindow(interp));
    if (!tkwin) return TCL_ERROR;
    IbusContext *ctx = FindContext(GetToplevelOfWidget(tkwin));
    if (!ctx) {
        Tcl_SetResult(interp, "No IBus context for this toplevel", TCL_STATIC);
        return TCL_ERROR;
    }
    IbusFocusIn(ctx);
    IbusEnable(ctx);
    return TCL_OK;
}

/*
 * ----------------------------------------------------------------------------
 * CmdFocusOut --
 *
 *         Informs IBus that a toplevel window has lost focus and disables the IME.
 *
 *
 * Results:
 *         Returns TCL_OK on success, TCL_ERROR on failure.
 *
 * Side effects:
 *         Sends FocusOut and Disable D-Bus calls to the IBus context.
 * ----------------------------------------------------------------------------
 */

static int CmdFocusOut(
		       ClientData clientData,
		       Tcl_Interp *interp,
                       int objc,
		       Tcl_Obj *const objv[])
{
    if (objc != 2) {
        Tcl_WrongNumArgs(interp, 1, objv, "window");
        return TCL_ERROR;
    }
    const char *winName = Tcl_GetString(objv[1]);
    Tk_Window tkwin = Tk_NameToWindow(interp, winName, Tk_MainWindow(interp));
    if (!tkwin) return TCL_ERROR;
    IbusContext *ctx = FindContext(GetToplevelOfWidget(tkwin));
    if (!ctx) return TCL_OK;
    IbusFocusOut(ctx);
    IbusDisable(ctx);
    return TCL_OK;
}

/*
 * ----------------------------------------------------------------------------
 * CmdProcessKey --
 *
 *         Sends a key event to IBus and returns whether the IME handled it.
 *
 * Results:
 *         Returns 1 if IBus handled the key event, 0 otherwise.
 *
 * Side effects:
 *         May start or update IME composition.
 * ----------------------------------------------------------------------------
 */

static int CmdProcessKey(ClientData clientData,
			 Tcl_Interp *interp,
                         int objc,
			 Tcl_Obj *const objv[])
{
    if (objc != 5) {
        Tcl_WrongNumArgs(interp, 1, objv, "window keyval keycode state");
        return TCL_ERROR;
    }
    const char *winName = Tcl_GetString(objv[1]);
    Tk_Window tkwin = Tk_NameToWindow(interp, winName, Tk_MainWindow(interp));
    if (!tkwin) return TCL_ERROR;

    uint32_t keyval, keycode, state;
    if (Tcl_GetIntFromObj(interp, objv[2], (int*)&keyval) != TCL_OK) return TCL_ERROR;
    if (Tcl_GetIntFromObj(interp, objv[3], (int*)&keycode) != TCL_OK) return TCL_ERROR;
    if (Tcl_GetIntFromObj(interp, objv[4], (int*)&state) != TCL_OK) return TCL_ERROR;

    IbusContext *ctx = FindContext(GetToplevelOfWidget(tkwin));
    if (!ctx) {
        Tcl_SetObjResult(interp, Tcl_NewIntObj(0));
        return TCL_OK;
    }
    int handled = IbusProcessKeyEvent(ctx, keyval, keycode, state);
    Tcl_SetObjResult(interp, Tcl_NewIntObj(handled));
    return TCL_OK;
}


/* Global to track the current D-Bus file descriptor. */
static int ibus_fd = -1;

/*
 *----------------------------------------------------------------------
 *
 * IbusBusHandler --
 *
 *   Tcl file handler callback for IBus D-Bus socket activity. Processes
 *   pending D-Bus messages from the IBus daemon when the file descriptor
 *   becomes readable. Includes re-entrancy protection to prevent concurrent
 *   processing when IBusProcessKeyEvent is already draining the bus.
 *
 * Results:
 *   None.
 *
 * Side effects:
 *   Processes incoming IBus messages (e.g., commit text, preedit updates,
 *   key event replies). May call sd_bus_process which can invoke IBus
 *   callbacks. Outputs debug messages to stderr when processing occurs.
 *
 *----------------------------------------------------------------------
 */

static void
IbusBusHandler(
    ClientData clientData,  /* sd_bus * for the IBus connection */
    int mask)               /* TCL_READABLE when fd has data */
{
    sd_bus *bus = (sd_bus *)clientData;
    if (!(mask & TCL_READABLE)) return;

    /*
     * Re-entrancy guard: IbusProcessKeyEvent may already be draining this
     * bus synchronously from inside a GLFW key callback.  Calling
     * sd_bus_process concurrently on the same bus is not safe; skip here
     * and let the in-progress drain handle any pending messages.  The Tcl
     * file handler will fire again on the next event-loop iteration if
     * data remains on the fd.
     */
    if (ibus_draining) {
        return;
    }

    fprintf(stderr, ">>> IbusBusHandler: processing IBus signals\n");

    int count = 0;
    int r;
    while ((r = sd_bus_process(bus, NULL)) > 0) {
        count++;
    }
    if (count > 0) {
        fprintf(stderr, "    Processed %d IBus message(s)\n", count);
    } else if (r < 0) {
        fprintf(stderr, "    sd_bus_process error: %s\n", strerror(-r));
    }
}

/*
 *----------------------------------------------------------------------
 *
 * IbusEventSetup --
 *
 *   Called by Tk's event loop integration to register or update the
 *   Tcl file handler for the IBus D-Bus socket. Ensures the file handler
 *   points to the current D-Bus connection file descriptor, cleaning up
 *   any previous handler if the fd has changed.
 *
 * Results:
 *   None.
 *
 * Side effects:
 *   May delete an existing Tcl file handler on the old IBus fd and
 *   create a new one on the current fd. Outputs debug message to stderr
 *   when a handler is registered.
 *
 *----------------------------------------------------------------------
 */

static void
IbusEventSetup(
    ClientData clientData,  /* Unused (may be NULL) */
    int flags)              /* TCL_WINDOW_EVENTS when setting up window events */
{
    if (!(flags & TCL_WINDOW_EVENTS) || !ibus_bus) return;

    int fd = sd_bus_get_fd(ibus_bus);
    if (fd < 0) return;

    if (fd != ibus_fd) {
        if (ibus_fd >= 0) {
            Tcl_DeleteFileHandler(ibus_fd);
        }
        Tcl_CreateFileHandler(fd, TCL_READABLE, IbusBusHandler, ibus_bus);
        ibus_fd = fd;
        fprintf(stderr, "IbusEventSetup: Registered handler for fd=%d\n", fd);
    }
}

/*
 *----------------------------------------------------------------------
 *
 * IbusEventCheck --
 *
 *   Called by Tk's event loop integration to determine if the IBus
 *   D-Bus socket has pending events that require processing. If events
 *   are available, sets the maximum block time to zero to ensure the
 *   event loop returns quickly and dispatches the file handler.
 *
 * Results:
 *   None.
 *
 * Side effects:
 *   May call Tcl_SetMaxBlockTime(&zero) when IBus events are pending,
 *   causing the Tcl event loop to avoid blocking and process the
 *   IBus file handler immediately.
 *
 *----------------------------------------------------------------------
 */

static void
IbusEventCheck(
    ClientData clientData,  /* Unused (may be NULL) */
    int flags)              /* TCL_WINDOW_EVENTS when checking window events */
{
    if (!(flags & TCL_WINDOW_EVENTS) || !ibus_bus) return;

    if (sd_bus_get_events(ibus_bus) > 0) {
        Tcl_Time zero = {0, 0};
        Tcl_SetMaxBlockTime(&zero);
    }
}
/*
 * ----------------------------------------------------------------------------
 * GetIbusAddress --
 *
 *         Resolve the IBus daemon's private D-Bus socket address.
 *
 *         IBus runs its own private D-Bus daemon and does NOT register on the
 *         generic session bus (DBUS_SESSION_BUS_ADDRESS).  Its socket address
 *         is advertised in two places, checked in order:
 *
 *           1. $IBUS_ADDRESS environment variable (set by ibus-daemon itself
 *              when it starts, or exported by the user's session).
 *
 *           2. The address file at
 *                ~/.config/ibus/bus/<machine-id>-unix-<suffix>
 *              IBus uses two suffix conventions depending on version and session
 *              type:
 *                Wayland (modern):  <WAYLAND_DISPLAY>      e.g. "wayland-0"
 *                Wayland (older):   <WAYLAND_DISPLAY>-0    e.g. "wayland-0-0"
 *                X11:               <display_num>-0        e.g. "0-0"
 *                X11 (unusual):     <display_num>          e.g. "0"
 *              All four are tried in that order.
 *
 *         The returned pointer is into a static buffer; copy it before the
 *         next call.  Returns NULL if the address cannot be found.
 *
 * Results:
 *         Returns a pointer to the IBus socket address string, or NULL.
 *
 * Side effects:
 *         None.
 * ----------------------------------------------------------------------------
 */

static const char *
GetIbusAddress(void)
{
    /* Prefer the environment variable set by ibus-daemon itself. */
    const char *env = getenv("IBUS_ADDRESS");
    if (env && *env) return env;

    /*
     * Fall back to the address file.
     * Path: ~/.config/ibus/bus/<dbus-machine-id>-unix-<display>-0
     */
    static char path[PATH_MAX];
    static char addr[4096];

    /* Read the D-Bus machine ID. */
    char machine_id[64] = "";
    FILE *f = fopen("/var/lib/dbus/machine-id", "r");
    if (!f) f = fopen("/etc/machine-id", "r");
    if (f) {
        if (fgets(machine_id, sizeof(machine_id), f)) {
            machine_id[strcspn(machine_id, "\r\n")] = '\0';
        }
        fclose(f);
    }
    if (!machine_id[0]) return NULL;

    const char *config_home = getenv("XDG_CONFIG_HOME");
    const char *home = getenv("HOME");
    const char *base = (config_home && *config_home) ? config_home : NULL;

    /*
     * IBus address file naming convention:
     *
     *   Wayland: <id>-unix-<WAYLAND_DISPLAY>          (no screen suffix)
     *            e.g. <id>-unix-wayland-0
     *   X11:     <id>-unix-<display_num>-<screen>
     *            e.g. <id>-unix-0-0  (from DISPLAY=:0.0 or :0)
     *
     * Older IBus versions append an extra "-0" to the Wayland name too, so
     * we try four candidates in order:
     *   1. <id>-unix-<WAYLAND_DISPLAY>        (modern Wayland, no screen)
     *   2. <id>-unix-<WAYLAND_DISPLAY>-0      (older Wayland, with screen)
     *   3. <id>-unix-<display_num>-0          (X11 with screen)
     *   4. <id>-unix-<display_num>            (X11 without screen, unusual)
     */
    const char *wayland_disp = getenv("WAYLAND_DISPLAY");
    if (!wayland_disp || !*wayland_disp) wayland_disp = "wayland-0";

    char x11_dnum[32] = "";
    const char *xdisp = getenv("DISPLAY");
    if (xdisp && *xdisp) {
        const char *p = xdisp + (xdisp[0] == ':' ? 1 : 0);
        const char *dot = strchr(p, '.');
        size_t len = dot ? (size_t)(dot - p) : strlen(p);
        if (len >= sizeof(x11_dnum)) len = sizeof(x11_dnum) - 1;
        strncpy(x11_dnum, p, len);
        x11_dnum[len] = '\0';
    }

    /* Build the four candidate suffixes. */
    char wayland_noscreen[64], wayland_screen[64];
    char x11_screen[64], x11_noscreen[64];
    snprintf(wayland_noscreen, sizeof(wayland_noscreen), "%s",    wayland_disp);
    snprintf(wayland_screen,   sizeof(wayland_screen),   "%s-0",  wayland_disp);
    snprintf(x11_screen,       sizeof(x11_screen),       "%s-0",  x11_dnum);
    snprintf(x11_noscreen,     sizeof(x11_noscreen),     "%s",    x11_dnum);

    const char *suffixes[4] = {
        wayland_noscreen,
        wayland_screen,
        x11_dnum[0] ? x11_screen    : NULL,
        x11_dnum[0] ? x11_noscreen  : NULL,
    };

    int i;
    for (i = 0; i < 4; i++) {
        if (!suffixes[i] || !suffixes[i][0]) continue;
        if (base) {
            snprintf(path, sizeof(path), "%s/ibus/bus/%s-unix-%s",
                     base, machine_id, suffixes[i]);
        } else {
            if (!home) continue;
            snprintf(path, sizeof(path), "%s/.config/ibus/bus/%s-unix-%s",
                     home, machine_id, suffixes[i]);
        }
        f = fopen(path, "r");
        if (!f) continue;

        char line[4096];
        addr[0] = '\0';
        while (fgets(line, sizeof(line), f)) {
            if (strncmp(line, "IBUS_ADDRESS=", 13) == 0) {
                strncpy(addr, line + 13, sizeof(addr) - 1);
                addr[sizeof(addr) - 1] = '\0';
                addr[strcspn(addr, "\r\n")] = '\0';
                break;
            }
        }
        fclose(f);
        if (addr[0]) {
            fprintf(stderr, "IBus: Found address file: %s\n", path);
            return addr;
        }
    }

    return NULL;
}

/*
 * ----------------------------------------------------------------------------
 * TkWaylandIbus_Init --
 *
 *         Initialize the IBus D-Bus connection, and
 *         integrate the D-Bus event source into the Tcl event loop.
 *
 *         IBus runs a private D-Bus daemon separate from the session bus.  We
 *         resolve its socket address via GetIbusAddress() (which checks
 *         $IBUS_ADDRESS first, then the address file in ~/.config/ibus/bus/)
 *         and connect directly to that socket with sd_bus_new /
 *         sd_bus_set_address / sd_bus_start.  Connecting to the generic
 *         session bus (sd_bus_default_user) does NOT work because IBus does
 *         not export its objects there.
 *
 *         If the IBus daemon is not running (common for non-CJK users) this
 *         function returns TCL_ERROR, which the caller treats as non-fatal.
 *
 * Results:
 *         Returns TCL_OK on success, TCL_ERROR if IBus is unavailable.
 *
 * Side effects:
 *         Connects to the IBus private bus, and sets up an event source.
 * ----------------------------------------------------------------------------
 */

int
TkWaylandIbus_Init(Tcl_Interp *interp)
{
    int r;

    const char *ibus_addr = GetIbusAddress();
    if (!ibus_addr) {
        fprintf(stderr, "IBus: Cannot find IBus daemon address "
                "(IBUS_ADDRESS not set and address file not found).\n");
        fprintf(stderr, "IME will be unavailable. To enable it, run:\n"
                "    ibus-daemon --daemonize --replace\n");
        return TCL_ERROR;
    }

    fprintf(stderr, "IBus: Connecting to %s\n", ibus_addr);

    r = sd_bus_new(&ibus_bus);
    if (r < 0) {
        fprintf(stderr, "IBus: sd_bus_new failed: %s\n", strerror(-r));
        ibus_bus = NULL;
        return TCL_ERROR;
    }

    r = sd_bus_set_address(ibus_bus, ibus_addr);
    if (r < 0) {
        fprintf(stderr, "IBus: sd_bus_set_address failed: %s\n", strerror(-r));
        sd_bus_unref(ibus_bus);
        ibus_bus = NULL;
        return TCL_ERROR;
    }

    r = sd_bus_start(ibus_bus);
    if (r < 0) {
        fprintf(stderr, "IBus: sd_bus_start failed: %s\n", strerror(-r));
        sd_bus_unref(ibus_bus);
        ibus_bus = NULL;
        return TCL_ERROR;
    }

    /*
     * Sanity-check: call GetGlobalEngine to confirm the IBus object exists.
     * This may fail when no engine is active (e.g. right after daemon start),
     * which is harmless.  A hard "object not found" would indicate the address
     * was wrong, but CreateInputContext will be the definitive test.
     */
    sd_bus_error error = SD_BUS_ERROR_NULL;
    sd_bus_message *reply = NULL;
    r = sd_bus_call_method(ibus_bus,
                           IBUS_SERVICE,
                           IBUS_PATH,
                           IBUS_INTERFACE,
                           "GetGlobalEngine",
                           &error, &reply, "");
    if (r < 0) {
        fprintf(stderr, "IBus: GetGlobalEngine: %s (continuing anyway)\n",
                error.message ? error.message : strerror(-r));
    } else {
        fprintf(stderr, "IBus: Connected and verified.\n");
    }
    if (reply) sd_bus_message_unref(reply);
    sd_bus_error_free(&error);

    /* Register event source for signals. */
    Tcl_CreateEventSource(IbusEventSetup, IbusEventCheck, NULL);

    /* Force initial setup. */
    IbusEventSetup(NULL, TCL_WINDOW_EVENTS);

    return TCL_OK;
}

/*
 * Local Variables:
 * mode: c
 * c-basic-offset: 4
 * fill-column: 78
 * End:
 */
