'\"
'\" Copyright (c) 1998-2000 by Scriptics Corporation.
'\" All rights reserved.
'\" 
'\" RCS: @(#) $Id: WinViewable.3,v 1.1 2000/04/18 02:18:32 ericm Exp $
'\" 
'\"
.so man.macros
.TH Tk_IsViewable 3 "" Tk "Tk Library Procedures"
.BS
.SH NAME
Tk_IsViewable \- determine whether a Tk window is viewable
.SH SYNOPSIS
.nf
\fB#include <tk.h>\fR
.sp
int
\fBTk_IsViewable\fR(\fItkwin\fR)
.SH ARGUMENTS
.AP Tk_Window tkwin
Window to examine.
.BE

.SH DESCRIPTION
.PP
\fBTk_IsViewable\fR is a utility function used to
determine whether or not a Tk window is viewable.  It returns
1 if the window given by \fItkwin\fR is viewable, and 0 if it is not.

.SH KEYWORDS
window, viewable
