/* 
 * tkIntPlatStubs.c --
 *
 *	This file contains the wrapper functions for the platform dependent
 *	unsupported Tk API.
 *
 * Copyright (c) 1998-1999 by Scriptics Corporation.
 * All rights reserved.
 *
 * RCS: @(#) $Id: tkIntPlatStubs.c,v 1.1.2.1 1999/03/06 00:08:04 redman Exp $
 */

#include "tkInt.h"
#include "tkPort.h"

/*
 * WARNING: This file is automatically generated by the tools/genStubs.tcl
 * script.  Any modifications to the function declarations below should be made
 * in the generic/tkInt.decls script.
 */

/* !BEGIN!: Do not edit below this line. */

/*
 * Exported stub functions:
 */

#ifdef __WIN32__
/* Slot 0 */
char *
TkAlignImageData(image, alignment, bitOrder)
    XImage * image;
    int alignment;
    int bitOrder;
{
    return (tkIntPlatStubsPtr->tkAlignImageData)(image, alignment, bitOrder);
}

/* Slot 1 */
void
TkClipBox(rgn, rect_return)
    TkRegion rgn;
    XRectangle* rect_return;
{
    (tkIntPlatStubsPtr->tkClipBox)(rgn, rect_return);
}

/* Slot 2 */
TkRegion
TkCreateRegion()
{
    return (tkIntPlatStubsPtr->tkCreateRegion)();
}

/* Slot 3 */
void
TkDestroyRegion(rgn)
    TkRegion rgn;
{
    (tkIntPlatStubsPtr->tkDestroyRegion)(rgn);
}

/* Slot 4 */
void
TkGenerateActivateEvents(winPtr, active)
    TkWindow * winPtr;
    int active;
{
    (tkIntPlatStubsPtr->tkGenerateActivateEvents)(winPtr, active);
}

/* Slot 5 */
void
TkIntersectRegion(sra, srcb, dr_return)
    TkRegion sra;
    TkRegion srcb;
    TkRegion dr_return;
{
    (tkIntPlatStubsPtr->tkIntersectRegion)(sra, srcb, dr_return);
}

/* Slot 6 */
unsigned long
TkpGetMS()
{
    return (tkIntPlatStubsPtr->tkpGetMS)();
}

/* Slot 7 */
void
TkPointerDeadWindow(winPtr)
    TkWindow * winPtr;
{
    (tkIntPlatStubsPtr->tkPointerDeadWindow)(winPtr);
}

/* Slot 8 */
void
TkpPrintWindowId(buf, window)
    char * buf;
    Window window;
{
    (tkIntPlatStubsPtr->tkpPrintWindowId)(buf, window);
}

/* Slot 9 */
int
TkpScanWindowId(interp, string, idPtr)
    Tcl_Interp * interp;
    char * string;
    int * idPtr;
{
    return (tkIntPlatStubsPtr->tkpScanWindowId)(interp, string, idPtr);
}

/* Slot 10 is reserved */
/* Slot 11 */
void
TkpSetCapture(winPtr)
    TkWindow * winPtr;
{
    (tkIntPlatStubsPtr->tkpSetCapture)(winPtr);
}

/* Slot 12 */
void
TkpSetCursor(cursor)
    TkpCursor cursor;
{
    (tkIntPlatStubsPtr->tkpSetCursor)(cursor);
}

/* Slot 13 */
void
TkpWmSetState(winPtr, state)
    TkWindow * winPtr;
    int state;
{
    (tkIntPlatStubsPtr->tkpWmSetState)(winPtr, state);
}

/* Slot 14 */
int
TkRectInRegion(rgn, x, y, width, height)
    TkRegion rgn;
    int x;
    int y;
    unsigned int width;
    unsigned int height;
{
    return (tkIntPlatStubsPtr->tkRectInRegion)(rgn, x, y, width, height);
}

/* Slot 15 */
void
TkSetPixmapColormap(pixmap, colormap)
    Pixmap pixmap;
    Colormap colormap;
{
    (tkIntPlatStubsPtr->tkSetPixmapColormap)(pixmap, colormap);
}

/* Slot 16 */
void
TkSetRegion(display, gc, rgn)
    Display* display;
    GC gc;
    TkRegion rgn;
{
    (tkIntPlatStubsPtr->tkSetRegion)(display, gc, rgn);
}

/* Slot 17 */
void
TkUnionRectWithRegion(rect, src, dr_return)
    XRectangle* rect;
    TkRegion src;
    TkRegion dr_return;
{
    (tkIntPlatStubsPtr->tkUnionRectWithRegion)(rect, src, dr_return);
}

/* Slot 18 */
void
TkWinCancelMouseTimer()
{
    (tkIntPlatStubsPtr->tkWinCancelMouseTimer)();
}

/* Slot 19 is reserved */
/* Slot 20 */
void
TkWinClipboardRender(dispPtr, format)
    TkDisplay * dispPtr;
    UINT format;
{
    (tkIntPlatStubsPtr->tkWinClipboardRender)(dispPtr, format);
}

/* Slot 21 */
LRESULT
TkWinEmbeddedEventProc(hwnd, message, wParam, lParam)
    HWND hwnd;
    UINT message;
    WPARAM wParam;
    LPARAM lParam;
{
    return (tkIntPlatStubsPtr->tkWinEmbeddedEventProc)(hwnd, message, wParam, lParam);
}

/* Slot 22 */
void
TkWinFillRect(dc, x, y, width, height, pixel)
    HDC dc;
    int x;
    int y;
    int width;
    int height;
    int pixel;
{
    (tkIntPlatStubsPtr->tkWinFillRect)(dc, x, y, width, height, pixel);
}

/* Slot 23 */
COLORREF
TkWinGetBorderPixels(tkwin, border, which)
    Tk_Window tkwin;
    Tk_3DBorder border;
    int which;
{
    return (tkIntPlatStubsPtr->tkWinGetBorderPixels)(tkwin, border, which);
}

/* Slot 24 */
HDC
TkWinGetDrawableDC(display, d, state)
    Display * display;
    Drawable d;
    TkWinDCState* state;
{
    return (tkIntPlatStubsPtr->tkWinGetDrawableDC)(display, d, state);
}

/* Slot 25 */
int
TkWinGetModifierState()
{
    return (tkIntPlatStubsPtr->tkWinGetModifierState)();
}

/* Slot 26 */
HPALETTE
TkWinGetSystemPalette()
{
    return (tkIntPlatStubsPtr->tkWinGetSystemPalette)();
}

/* Slot 27 */
HWND
TkWinGetWrapperWindow(tkwin)
    Tk_Window tkwin;
{
    return (tkIntPlatStubsPtr->tkWinGetWrapperWindow)(tkwin);
}

/* Slot 28 */
int
TkWinHandleMenuEvent(phwnd, pMessage, pwParam, plParam, plResult)
    HWND * phwnd;
    UINT * pMessage;
    WPARAM * pwParam;
    LPARAM * plParam;
    LRESULT * plResult;
{
    return (tkIntPlatStubsPtr->tkWinHandleMenuEvent)(phwnd, pMessage, pwParam, plParam, plResult);
}

/* Slot 29 */
int
TkWinIndexOfColor(colorPtr)
    XColor * colorPtr;
{
    return (tkIntPlatStubsPtr->tkWinIndexOfColor)(colorPtr);
}

/* Slot 30 */
void
TkWinPointerDeadWindow(winPtr)
    TkWindow * winPtr;
{
    (tkIntPlatStubsPtr->tkWinPointerDeadWindow)(winPtr);
}

/* Slot 31 */
void
TkWinPointerEvent(hwnd, x, y)
    HWND hwnd;
    int x;
    int y;
{
    (tkIntPlatStubsPtr->tkWinPointerEvent)(hwnd, x, y);
}

/* Slot 32 */
void
TkWinPointerInit()
{
    (tkIntPlatStubsPtr->tkWinPointerInit)();
}

/* Slot 33 */
LRESULT
TkWinReflectMessage(hwnd, message, wParam, lParam)
    HWND hwnd;
    UINT message;
    WPARAM wParam;
    LPARAM lParam;
{
    return (tkIntPlatStubsPtr->tkWinReflectMessage)(hwnd, message, wParam, lParam);
}

/* Slot 34 */
void
TkWinReleaseDrawableDC(d, hdc, state)
    Drawable d;
    HDC hdc;
    TkWinDCState* state;
{
    (tkIntPlatStubsPtr->tkWinReleaseDrawableDC)(d, hdc, state);
}

/* Slot 35 */
LRESULT
TkWinResendEvent(wndproc, hwnd, eventPtr)
    WNDPROC wndproc;
    HWND hwnd;
    XEvent * eventPtr;
{
    return (tkIntPlatStubsPtr->tkWinResendEvent)(wndproc, hwnd, eventPtr);
}

/* Slot 36 */
HPALETTE
TkWinSelectPalette(dc, colormap)
    HDC dc;
    Colormap colormap;
{
    return (tkIntPlatStubsPtr->tkWinSelectPalette)(dc, colormap);
}

/* Slot 37 */
void
TkWinSetMenu(tkwin, hMenu)
    Tk_Window tkwin;
    HMENU hMenu;
{
    (tkIntPlatStubsPtr->tkWinSetMenu)(tkwin, hMenu);
}

/* Slot 38 */
void
TkWinSetWindowPos(hwnd, siblingHwnd, pos)
    HWND hwnd;
    HWND siblingHwnd;
    int pos;
{
    (tkIntPlatStubsPtr->tkWinSetWindowPos)(hwnd, siblingHwnd, pos);
}

/* Slot 39 */
void
TkWinUpdateCursor(winPtr)
    TkWindow * winPtr;
{
    (tkIntPlatStubsPtr->tkWinUpdateCursor)(winPtr);
}

/* Slot 40 */
void
TkWinWmCleanup(hInstance)
    HINSTANCE hInstance;
{
    (tkIntPlatStubsPtr->tkWinWmCleanup)(hInstance);
}

/* Slot 41 */
HWND
TkWinWmFindEmbedAssociation(winPtr)
    TkWindow * winPtr;
{
    return (tkIntPlatStubsPtr->tkWinWmFindEmbedAssociation)(winPtr);
}

/* Slot 42 */
void
TkWinWmStoreEmbedAssociation(winPtr, hwnd)
    TkWindow * winPtr;
    HWND hwnd;
{
    (tkIntPlatStubsPtr->tkWinWmStoreEmbedAssociation)(winPtr, hwnd);
}

/* Slot 43 */
void
TkWinXCleanup(hInstance)
    HINSTANCE hInstance;
{
    (tkIntPlatStubsPtr->tkWinXCleanup)(hInstance);
}

/* Slot 44 */
void
TkWinXInit(hInstance)
    HINSTANCE hInstance;
{
    (tkIntPlatStubsPtr->tkWinXInit)(hInstance);
}

#endif /* __WIN32__ */
#if !defined(__WIN32__) && !defined(MAC_TCL)
/* Slot 0 */
void
TkCreateXEventSource()
{
    (tkIntPlatStubsPtr->tkCreateXEventSource)();
}

/* Slot 1 */
void
TkFreeWindowId(dispPtr, w)
    TkDisplay * dispPtr;
    Window w;
{
    (tkIntPlatStubsPtr->tkFreeWindowId)(dispPtr, w);
}

/* Slot 2 */
void
TkInitXId(dispPtr)
    TkDisplay * dispPtr;
{
    (tkIntPlatStubsPtr->tkInitXId)(dispPtr);
}

/* Slot 3 */
TkWindow *
TkpGetContainer(embeddedPtr)
    TkWindow * embeddedPtr;
{
    return (tkIntPlatStubsPtr->tkpGetContainer)(embeddedPtr);
}

/* Slot 4 */
int
TkpCmapStressed(tkwin, colormap)
    Tk_Window tkwin;
    Colormap colormap;
{
    return (tkIntPlatStubsPtr->tkpCmapStressed)(tkwin, colormap);
}

/* Slot 5 */
void
TkpSync(display)
    Display * display;
{
    (tkIntPlatStubsPtr->tkpSync)(display);
}

/* Slot 6 */
Window
TkUnixContainerId(winPtr)
    TkWindow * winPtr;
{
    return (tkIntPlatStubsPtr->tkUnixContainerId)(winPtr);
}

/* Slot 7 */
int
TkUnixDoOneXEvent(timePtr)
    Tcl_Time * timePtr;
{
    return (tkIntPlatStubsPtr->tkUnixDoOneXEvent)(timePtr);
}

/* Slot 8 */
void
TkUnixSetMenubar(tkwin, menubar)
    Tk_Window tkwin;
    Tk_Window menubar;
{
    (tkIntPlatStubsPtr->tkUnixSetMenubar)(tkwin, menubar);
}

#endif /* UNIX */
#ifdef MAC_TCL
/* Slot 0 */
void
TkClipBox(rgn, rect_return)
    TkRegion rgn;
    XRectangle* rect_return;
{
    (tkIntPlatStubsPtr->tkClipBox)(rgn, rect_return);
}

/* Slot 1 */
TkRegion
TkCreateRegion()
{
    return (tkIntPlatStubsPtr->tkCreateRegion)();
}

/* Slot 2 */
void
TkDestroyRegion(rgn)
    TkRegion rgn;
{
    (tkIntPlatStubsPtr->tkDestroyRegion)(rgn);
}

/* Slot 3 */
void
TkGenerateActivateEvents(winPtr, active)
    TkWindow * winPtr;
    int active;
{
    (tkIntPlatStubsPtr->tkGenerateActivateEvents)(winPtr, active);
}

/* Slot 4 */
void
TkIntersectRegion(sra, srcb, dr_return)
    TkRegion sra;
    TkRegion srcb;
    TkRegion dr_return;
{
    (tkIntPlatStubsPtr->tkIntersectRegion)(sra, srcb, dr_return);
}

/* Slot 5 */
Pixmap
TkpCreateNativeBitmap(display, source)
    Display * display;
    char * source;
{
    return (tkIntPlatStubsPtr->tkpCreateNativeBitmap)(display, source);
}

/* Slot 6 */
void
TkpDefineNativeBitmaps()
{
    (tkIntPlatStubsPtr->tkpDefineNativeBitmaps)();
}

/* Slot 7 */
unsigned long
TkpGetMS()
{
    return (tkIntPlatStubsPtr->tkpGetMS)();
}

/* Slot 8 */
Pixmap
TkpGetNativeAppBitmap(display, name, width, height)
    Display * display;
    char * name;
    int * width;
    int * height;
{
    return (tkIntPlatStubsPtr->tkpGetNativeAppBitmap)(display, name, width, height);
}

/* Slot 9 */
void
TkPointerDeadWindow(winPtr)
    TkWindow * winPtr;
{
    (tkIntPlatStubsPtr->tkPointerDeadWindow)(winPtr);
}

/* Slot 10 */
void
TkpSetCapture(winPtr)
    TkWindow * winPtr;
{
    (tkIntPlatStubsPtr->tkpSetCapture)(winPtr);
}

/* Slot 11 */
void
TkpSetCursor(cursor)
    TkpCursor cursor;
{
    (tkIntPlatStubsPtr->tkpSetCursor)(cursor);
}

/* Slot 12 is reserved */
/* Slot 13 */
void
TkpWmSetState(winPtr, state)
    TkWindow * winPtr;
    int state;
{
    (tkIntPlatStubsPtr->tkpWmSetState)(winPtr, state);
}

/* Slot 14 */
int
TkRectInRegion(rgn, x, y, width, height)
    TkRegion rgn;
    int x;
    int y;
    unsigned int width;
    unsigned int height;
{
    return (tkIntPlatStubsPtr->tkRectInRegion)(rgn, x, y, width, height);
}

/* Slot 15 */
void
TkSetRegion(display, gc, rgn)
    Display* display;
    GC gc;
    TkRegion rgn;
{
    (tkIntPlatStubsPtr->tkSetRegion)(display, gc, rgn);
}

/* Slot 16 */
void
TkUnionRectWithRegion(rect, src, dr_return)
    XRectangle* rect;
    TkRegion src;
    TkRegion dr_return;
{
    (tkIntPlatStubsPtr->tkUnionRectWithRegion)(rect, src, dr_return);
}

/* Slot 17 */
int
HandleWMEvent(theEvent)
    EventRecord * theEvent;
{
    return (tkIntPlatStubsPtr->handleWMEvent)(theEvent);
}

/* Slot 18 */
void
TkAboutDlg()
{
    (tkIntPlatStubsPtr->tkAboutDlg)();
}

/* Slot 19 */
void
TkCreateMacEventSource()
{
    (tkIntPlatStubsPtr->tkCreateMacEventSource)();
}

/* Slot 20 */
void
TkFontList(interp, display)
    Tcl_Interp * interp;
    Display * display;
{
    (tkIntPlatStubsPtr->tkFontList)(interp, display);
}

/* Slot 21 */
Window
TkGetTransientMaster(winPtr)
    TkWindow * winPtr;
{
    return (tkIntPlatStubsPtr->tkGetTransientMaster)(winPtr);
}

/* Slot 22 */
int
TkGenerateButtonEvent(x, y, window, state)
    int x;
    int y;
    Window window;
    unsigned int state;
{
    return (tkIntPlatStubsPtr->tkGenerateButtonEvent)(x, y, window, state);
}

/* Slot 23 */
int
TkGetCharPositions(font_struct, string, count, buffer)
    XFontStruct * font_struct;
    char * string;
    int count;
    short * buffer;
{
    return (tkIntPlatStubsPtr->tkGetCharPositions)(font_struct, string, count, buffer);
}

/* Slot 24 */
void
TkGenWMDestroyEvent(tkwin)
    Tk_Window tkwin;
{
    (tkIntPlatStubsPtr->tkGenWMDestroyEvent)(tkwin);
}

/* Slot 25 */
void
TkGenWMConfigureEvent(tkwin, x, y, width, height, flags)
    Tk_Window tkwin;
    int x;
    int y;
    int width;
    int height;
    int flags;
{
    (tkIntPlatStubsPtr->tkGenWMConfigureEvent)(tkwin, x, y, width, height, flags);
}

/* Slot 26 */
unsigned int
TkMacButtonKeyState()
{
    return (tkIntPlatStubsPtr->tkMacButtonKeyState)();
}

/* Slot 27 */
void
TkMacClearMenubarActive()
{
    (tkIntPlatStubsPtr->tkMacClearMenubarActive)();
}

/* Slot 28 */
int
TkMacConvertEvent(eventPtr)
    EventRecord * eventPtr;
{
    return (tkIntPlatStubsPtr->tkMacConvertEvent)(eventPtr);
}

/* Slot 29 */
int
TkMacDispatchMenuEvent(menuID, index)
    int menuID;
    int index;
{
    return (tkIntPlatStubsPtr->tkMacDispatchMenuEvent)(menuID, index);
}

/* Slot 30 */
void
TkMacInstallCursor(resizeOverride)
    int resizeOverride;
{
    (tkIntPlatStubsPtr->tkMacInstallCursor)(resizeOverride);
}

/* Slot 31 */
int
TkMacConvertTkEvent(eventPtr, window)
    EventRecord * eventPtr;
    Window window;
{
    return (tkIntPlatStubsPtr->tkMacConvertTkEvent)(eventPtr, window);
}

/* Slot 32 */
void
TkMacHandleTearoffMenu()
{
    (tkIntPlatStubsPtr->tkMacHandleTearoffMenu)();
}

/* Slot 33 */
void
tkMacInstallMWConsole(interp)
    Tcl_Interp * interp;
{
    (tkIntPlatStubsPtr->tkMacInstallMWConsole)(interp);
}

/* Slot 34 */
void
TkMacInvalClipRgns(winPtr)
    TkWindow * winPtr;
{
    (tkIntPlatStubsPtr->tkMacInvalClipRgns)(winPtr);
}

/* Slot 35 */
void
TkMacDoHLEvent(theEvent)
    EventRecord * theEvent;
{
    (tkIntPlatStubsPtr->tkMacDoHLEvent)(theEvent);
}

/* Slot 36 */
void
TkMacFontInfo(fontId, family, style, size)
    Font fontId;
    short * family;
    short * style;
    short * size;
{
    (tkIntPlatStubsPtr->tkMacFontInfo)(fontId, family, style, size);
}

/* Slot 37 */
Time
TkMacGenerateTime()
{
    return (tkIntPlatStubsPtr->tkMacGenerateTime)();
}

/* Slot 38 */
GWorldPtr
TkMacGetDrawablePort(drawable)
    Drawable drawable;
{
    return (tkIntPlatStubsPtr->tkMacGetDrawablePort)(drawable);
}

/* Slot 39 */
TkWindow *
TkMacGetScrollbarGrowWindow(winPtr)
    TkWindow * winPtr;
{
    return (tkIntPlatStubsPtr->tkMacGetScrollbarGrowWindow)(winPtr);
}

/* Slot 40 */
Window
TkMacGetXWindow(macWinPtr)
    WindowRef macWinPtr;
{
    return (tkIntPlatStubsPtr->tkMacGetXWindow)(macWinPtr);
}

/* Slot 41 */
int
TkMacGrowToplevel(whichWindow, start)
    WindowRef whichWindow;
    Point start;
{
    return (tkIntPlatStubsPtr->tkMacGrowToplevel)(whichWindow, start);
}

/* Slot 42 */
void
TkMacHandleMenuSelect(mResult, optionKeyPressed)
    long mResult;
    int optionKeyPressed;
{
    (tkIntPlatStubsPtr->tkMacHandleMenuSelect)(mResult, optionKeyPressed);
}

/* Slot 43 */
int
TkMacHaveAppearance()
{
    return (tkIntPlatStubsPtr->tkMacHaveAppearance)();
}

/* Slot 44 */
void
TkMacInitAppleEvents(interp)
    Tcl_Interp * interp;
{
    (tkIntPlatStubsPtr->tkMacInitAppleEvents)(interp);
}

/* Slot 45 */
void
TkMacInitMenus(interp)
    Tcl_Interp * interp;
{
    (tkIntPlatStubsPtr->tkMacInitMenus)(interp);
}

/* Slot 46 */
void
TkMacInvalidateWindow(macWin, flag)
    MacDrawable * macWin;
    int flag;
{
    (tkIntPlatStubsPtr->tkMacInvalidateWindow)(macWin, flag);
}

/* Slot 47 */
int
TkMacIsCharacterMissing(tkfont, searchChar)
    Tk_Font tkfont;
    unsigned int searchChar;
{
    return (tkIntPlatStubsPtr->tkMacIsCharacterMissing)(tkfont, searchChar);
}

/* Slot 48 */
void
TkMacMakeRealWindowExist(winPtr)
    TkWindow * winPtr;
{
    (tkIntPlatStubsPtr->tkMacMakeRealWindowExist)(winPtr);
}

/* Slot 49 */
BitMapPtr
TkMacMakeStippleMap(d1, d2)
    Drawable d1;
    Drawable d2;
{
    return (tkIntPlatStubsPtr->tkMacMakeStippleMap)(d1, d2);
}

/* Slot 50 */
void
TkMacMenuClick()
{
    (tkIntPlatStubsPtr->tkMacMenuClick)();
}

/* Slot 51 */
void
TkMacRegisterOffScreenWindow(window, portPtr)
    Window window;
    GWorldPtr portPtr;
{
    (tkIntPlatStubsPtr->tkMacRegisterOffScreenWindow)(window, portPtr);
}

/* Slot 52 */
int
TkMacResizable(winPtr)
    TkWindow * winPtr;
{
    return (tkIntPlatStubsPtr->tkMacResizable)(winPtr);
}

/* Slot 53 */
void
TkMacSetEmbedRgn(winPtr, rgn)
    TkWindow * winPtr;
    RgnHandle rgn;
{
    (tkIntPlatStubsPtr->tkMacSetEmbedRgn)(winPtr, rgn);
}

/* Slot 54 */
void
TkMacSetHelpMenuItemCount()
{
    (tkIntPlatStubsPtr->tkMacSetHelpMenuItemCount)();
}

/* Slot 55 */
void
TkMacSetScrollbarGrow(winPtr, flag)
    TkWindow * winPtr;
    int flag;
{
    (tkIntPlatStubsPtr->tkMacSetScrollbarGrow)(winPtr, flag);
}

/* Slot 56 */
void
TkMacSetUpClippingRgn(drawable)
    Drawable drawable;
{
    (tkIntPlatStubsPtr->tkMacSetUpClippingRgn)(drawable);
}

/* Slot 57 */
void
TkMacSetUpGraphicsPort(gc)
    GC gc;
{
    (tkIntPlatStubsPtr->tkMacSetUpGraphicsPort)(gc);
}

/* Slot 58 */
void
TkMacUpdateClipRgn(winPtr)
    TkWindow * winPtr;
{
    (tkIntPlatStubsPtr->tkMacUpdateClipRgn)(winPtr);
}

/* Slot 59 */
void
TkMacUnregisterMacWindow(portPtr)
    GWorldPtr portPtr;
{
    (tkIntPlatStubsPtr->tkMacUnregisterMacWindow)(portPtr);
}

/* Slot 60 */
int
TkMacUseMenuID(macID)
    short macID;
{
    return (tkIntPlatStubsPtr->tkMacUseMenuID)(macID);
}

/* Slot 61 */
RgnHandle
TkMacVisableClipRgn(winPtr)
    TkWindow * winPtr;
{
    return (tkIntPlatStubsPtr->tkMacVisableClipRgn)(winPtr);
}

/* Slot 62 */
void
TkMacWinBounds(winPtr, geometry)
    TkWindow * winPtr;
    Rect * geometry;
{
    (tkIntPlatStubsPtr->tkMacWinBounds)(winPtr, geometry);
}

/* Slot 63 */
void
TkMacWindowOffset(wRef, xOffset, yOffset)
    WindowRef wRef;
    int * xOffset;
    int * yOffset;
{
    (tkIntPlatStubsPtr->tkMacWindowOffset)(wRef, xOffset, yOffset);
}

/* Slot 64 */
void
TkResumeClipboard()
{
    (tkIntPlatStubsPtr->tkResumeClipboard)();
}

/* Slot 65 */
int
TkSetMacColor(pixel, macColor)
    unsigned long pixel;
    RGBColor * macColor;
{
    return (tkIntPlatStubsPtr->tkSetMacColor)(pixel, macColor);
}

/* Slot 66 */
void
TkSetWMName(winPtr, titleUid)
    TkWindow * winPtr;
    Tk_Uid titleUid;
{
    (tkIntPlatStubsPtr->tkSetWMName)(winPtr, titleUid);
}

/* Slot 67 */
void
TkSuspendClipboard()
{
    (tkIntPlatStubsPtr->tkSuspendClipboard)();
}

/* Slot 68 */
int
TkWMGrowToplevel(whichWindow, start)
    WindowRef whichWindow;
    Point start;
{
    return (tkIntPlatStubsPtr->tkWMGrowToplevel)(whichWindow, start);
}

/* Slot 69 */
int
TkMacZoomToplevel(whichWindow, where, zoomPart)
    WindowPtr whichWindow;
    Point where;
    short zoomPart;
{
    return (tkIntPlatStubsPtr->tkMacZoomToplevel)(whichWindow, where, zoomPart);
}

/* Slot 70 */
Tk_Window
Tk_TopCoordsToWindow(tkwin, rootX, rootY, newX, newY)
    Tk_Window tkwin;
    int rootX;
    int rootY;
    int * newX;
    int * newY;
{
    return (tkIntPlatStubsPtr->tk_TopCoordsToWindow)(tkwin, rootX, rootY, newX, newY);
}

/* Slot 71 */
MacDrawable *
TkMacContainerId(winPtr)
    TkWindow * winPtr;
{
    return (tkIntPlatStubsPtr->tkMacContainerId)(winPtr);
}

/* Slot 72 */
MacDrawable *
TkMacGetHostToplevel(winPtr)
    TkWindow * winPtr;
{
    return (tkIntPlatStubsPtr->tkMacGetHostToplevel)(winPtr);
}

#endif /* MAC_TCL */

/* !END!: Do not edit above this line. */
