/* 
 * tkStubInit.c --
 *
 *	This file contains the initializers for the Tk stub vectors.
 *
 * Copyright (c) 1998-1999 by Scriptics Corporation.
 *
 * See the file "license.terms" for information on usage and redistribution
 * of this file, and for a DISCLAIMER OF ALL WARRANTIES.
 *
 * RCS: @(#) $Id: tkStubInit.c,v 1.1.2.2 1999/03/06 01:54:59 redman Exp $
 */

#include "tkInt.h"
#include "tkPort.h"

/*
 * Remove macros that will interfere with the definitions below.
 */

/*
 * WARNING: The contents of this file is automatically generated by the
 * tools/genStubs.tcl script. Any modifications to the function declarations
 * below should be made in the generic/tk.decls script.
 */

/* !BEGIN!: Do not edit below this line. */

static TkStubHooks tkStubHooks;

TkStubs tkStubs = {
    TCL_STUB_MAGIC,
    &tkStubHooks,
    Tk_MainLoop, /* 0 */
    Tk_3DBorderColor, /* 1 */
    Tk_3DBorderGC, /* 2 */
    Tk_3DHorizontalBevel, /* 3 */
    Tk_3DVerticalBevel, /* 4 */
    Tk_AddOption, /* 5 */
    Tk_BindEvent, /* 6 */
    Tk_CanvasDrawableCoords, /* 7 */
    Tk_CanvasEventuallyRedraw, /* 8 */
    Tk_CanvasGetCoord, /* 9 */
    Tk_CanvasGetTextInfo, /* 10 */
    Tk_CanvasPsBitmap, /* 11 */
    Tk_CanvasPsColor, /* 12 */
    Tk_CanvasPsFont, /* 13 */
    Tk_CanvasPsPath, /* 14 */
    Tk_CanvasPsStipple, /* 15 */
    Tk_CanvasPsY, /* 16 */
    Tk_CanvasSetStippleOrigin, /* 17 */
    Tk_CanvasTagsParseProc, /* 18 */
    Tk_CanvasTagsPrintProc, /* 19 */
    Tk_CanvasTkwin, /* 20 */
    Tk_CanvasWindowCoords, /* 21 */
    Tk_ChangeWindowAttributes, /* 22 */
    Tk_CharBbox, /* 23 */
    Tk_ClearSelection, /* 24 */
    Tk_ClipboardAppend, /* 25 */
    Tk_ClipboardClear, /* 26 */
    Tk_ConfigureInfo, /* 27 */
    Tk_ConfigureValue, /* 28 */
    Tk_ConfigureWidget, /* 29 */
    Tk_ConfigureWindow, /* 30 */
    Tk_ComputeTextLayout, /* 31 */
    Tk_CoordsToWindow, /* 32 */
    Tk_CreateBinding, /* 33 */
    Tk_CreateBindingTable, /* 34 */
    Tk_CreateErrorHandler, /* 35 */
    Tk_CreateEventHandler, /* 36 */
    Tk_CreateGenericHandler, /* 37 */
    Tk_CreateImageType, /* 38 */
    Tk_CreateItemType, /* 39 */
    Tk_CreatePhotoImageFormat, /* 40 */
    Tk_CreateSelHandler, /* 41 */
    Tk_CreateWindow, /* 42 */
    Tk_CreateWindowFromPath, /* 43 */
    Tk_DefineBitmap, /* 44 */
    Tk_DefineCursor, /* 45 */
    Tk_DeleteAllBindings, /* 46 */
    Tk_DeleteBinding, /* 47 */
    Tk_DeleteBindingTable, /* 48 */
    Tk_DeleteErrorHandler, /* 49 */
    Tk_DeleteEventHandler, /* 50 */
    Tk_DeleteGenericHandler, /* 51 */
    Tk_DeleteImage, /* 52 */
    Tk_DeleteSelHandler, /* 53 */
    Tk_DestroyWindow, /* 54 */
    Tk_DisplayName, /* 55 */
    Tk_DistanceToTextLayout, /* 56 */
    Tk_Draw3DPolygon, /* 57 */
    Tk_Draw3DRectangle, /* 58 */
    Tk_DrawChars, /* 59 */
    Tk_DrawFocusHighlight, /* 60 */
    Tk_DrawTextLayout, /* 61 */
    Tk_Fill3DPolygon, /* 62 */
    Tk_Fill3DRectangle, /* 63 */
    Tk_FindPhoto, /* 64 */
    Tk_FontId, /* 65 */
    Tk_Free3DBorder, /* 66 */
    Tk_FreeBitmap, /* 67 */
    Tk_FreeColor, /* 68 */
    Tk_FreeColormap, /* 69 */
    Tk_FreeCursor, /* 70 */
    Tk_FreeFont, /* 71 */
    Tk_FreeGC, /* 72 */
    Tk_FreeImage, /* 73 */
    Tk_FreeOptions, /* 74 */
    Tk_FreePixmap, /* 75 */
    Tk_FreeTextLayout, /* 76 */
    Tk_FreeXId, /* 77 */
    Tk_GCForColor, /* 78 */
    Tk_GeometryRequest, /* 79 */
    Tk_Get3DBorder, /* 80 */
    Tk_GetAllBindings, /* 81 */
    Tk_GetAnchor, /* 82 */
    Tk_GetAtomName, /* 83 */
    Tk_GetBinding, /* 84 */
    Tk_GetBitmap, /* 85 */
    Tk_GetBitmapFromData, /* 86 */
    Tk_GetCapStyle, /* 87 */
    Tk_GetColor, /* 88 */
    Tk_GetColorByValue, /* 89 */
    Tk_GetColormap, /* 90 */
    Tk_GetCursor, /* 91 */
    Tk_GetCursorFromData, /* 92 */
    Tk_GetFont, /* 93 */
    Tk_GetFontFromObj, /* 94 */
    Tk_GetFontMetrics, /* 95 */
    Tk_GetGC, /* 96 */
    Tk_GetImage, /* 97 */
    Tk_GetImageMasterData, /* 98 */
    Tk_GetItemTypes, /* 99 */
    Tk_GetJoinStyle, /* 100 */
    Tk_GetJustify, /* 101 */
    Tk_GetNumMainWindows, /* 102 */
    Tk_GetOption, /* 103 */
    Tk_GetPixels, /* 104 */
    Tk_GetPixmap, /* 105 */
    Tk_GetRelief, /* 106 */
    Tk_GetRootCoords, /* 107 */
    Tk_GetScrollInfo, /* 108 */
    Tk_GetScreenMM, /* 109 */
    Tk_GetSelection, /* 110 */
    Tk_GetUid, /* 111 */
    Tk_GetVisual, /* 112 */
    Tk_GetVRootGeometry, /* 113 */
    Tk_Grab, /* 114 */
    Tk_HandleEvent, /* 115 */
    Tk_IdToWindow, /* 116 */
    Tk_ImageChanged, /* 117 */
    Tk_Init, /* 118 */
    Tk_InternAtom, /* 119 */
    Tk_IntersectTextLayout, /* 120 */
    Tk_Main, /* 121 */
    Tk_MaintainGeometry, /* 122 */
    Tk_MainWindow, /* 123 */
    Tk_MakeWindowExist, /* 124 */
    Tk_ManageGeometry, /* 125 */
    Tk_MapWindow, /* 126 */
    Tk_MeasureChars, /* 127 */
    Tk_MoveResizeWindow, /* 128 */
    Tk_MoveWindow, /* 129 */
    Tk_MoveToplevelWindow, /* 130 */
    Tk_NameOf3DBorder, /* 131 */
    Tk_NameOfAnchor, /* 132 */
    Tk_NameOfBitmap, /* 133 */
    Tk_NameOfCapStyle, /* 134 */
    Tk_NameOfColor, /* 135 */
    Tk_NameOfCursor, /* 136 */
    Tk_NameOfFont, /* 137 */
    Tk_NameOfImage, /* 138 */
    Tk_NameOfJoinStyle, /* 139 */
    Tk_NameOfJustify, /* 140 */
    Tk_NameOfRelief, /* 141 */
    Tk_NameToWindow, /* 142 */
    Tk_OwnSelection, /* 143 */
    Tk_ParseArgv, /* 144 */
    Tk_PhotoPutBlock, /* 145 */
    Tk_PhotoPutZoomedBlock, /* 146 */
    Tk_PhotoGetImage, /* 147 */
    Tk_PhotoBlank, /* 148 */
    Tk_PhotoExpand, /* 149 */
    Tk_PhotoGetSize, /* 150 */
    Tk_PhotoSetSize, /* 151 */
    Tk_PointToChar, /* 152 */
    Tk_PostscriptFontName, /* 153 */
    Tk_PreserveColormap, /* 154 */
    Tk_QueueWindowEvent, /* 155 */
    Tk_RedrawImage, /* 156 */
    Tk_ResizeWindow, /* 157 */
    Tk_RestackWindow, /* 158 */
    Tk_RestrictEvents, /* 159 */
    Tk_SafeInit, /* 160 */
    Tk_SetAppName, /* 161 */
    Tk_SetBackgroundFromBorder, /* 162 */
    Tk_SetClass, /* 163 */
    Tk_SetGrid, /* 164 */
    Tk_SetInternalBorder, /* 165 */
    Tk_SetWindowBackground, /* 166 */
    Tk_SetWindowBackgroundPixmap, /* 167 */
    Tk_SetWindowBorder, /* 168 */
    Tk_SetWindowBorderWidth, /* 169 */
    Tk_SetWindowBorderPixmap, /* 170 */
    Tk_SetWindowColormap, /* 171 */
    Tk_SetWindowVisual, /* 172 */
    Tk_SizeOfBitmap, /* 173 */
    Tk_SizeOfImage, /* 174 */
    Tk_StrictMotif, /* 175 */
    Tk_TextLayoutToPostscript, /* 176 */
    Tk_TextWidth, /* 177 */
    Tk_UndefineCursor, /* 178 */
    Tk_UnderlineChars, /* 179 */
    Tk_UnderlineTextLayout, /* 180 */
    Tk_Ungrab, /* 181 */
    Tk_UnmaintainGeometry, /* 182 */
    Tk_UnmapWindow, /* 183 */
    Tk_UnsetGrid, /* 184 */
    Tk_UpdatePointer, /* 185 */
};

extern TkStubs *tkStubsPtr = &tkStubs;

TkIntStubs tkIntStubs = {
    TCL_STUB_MAGIC,
    NULL,
    TkAllocWindow, /* 0 */
    TkBezierPoints, /* 1 */
    TkBezierScreenPoints, /* 2 */
    TkBindDeadWindow, /* 3 */
    TkBindEventProc, /* 4 */
    TkBindFree, /* 5 */
    TkBindInit, /* 6 */
    TkChangeEventWindow, /* 7 */
    TkClipInit, /* 8 */
    TkComputeAnchor, /* 9 */
    TkCopyAndGlobalEval, /* 10 */
    TkCreateBindingProcedure, /* 11 */
    TkCreateCursorFromData, /* 12 */
    TkCreateFrame, /* 13 */
    TkCreateMainWindow, /* 14 */
    TkCurrentTime, /* 15 */
    TkDeleteAllImages, /* 16 */
    TkDoConfigureNotify, /* 17 */
    TkDrawInsetFocusHighlight, /* 18 */
    TkEventDeadWindow, /* 19 */
    TkFillPolygon, /* 20 */
    TkFindStateNum, /* 21 */
    TkFindStateString, /* 22 */
    TkFocusDeadWindow, /* 23 */
    TkFocusFilterEvent, /* 24 */
    TkFocusKeyEvent, /* 25 */
    TkFontPkgInit, /* 26 */
    TkFontPkgFree, /* 27 */
    TkFreeBindingTags, /* 28 */
    TkFreeCursor, /* 29 */
    TkGetBitmapData, /* 30 */
    TkGetButtPoints, /* 31 */
    TkGetCursorByName, /* 32 */
    TkGetDefaultScreenName, /* 33 */
    TkGetDisplay, /* 34 */
    TkGetDisplayOf, /* 35 */
    TkGetFocusWin, /* 36 */
    TkGetInterpNames, /* 37 */
    TkGetMiterPoints, /* 38 */
    TkGetPointerCoords, /* 39 */
    TkGetServerInfo, /* 40 */
    TkGrabDeadWindow, /* 41 */
    TkGrabState, /* 42 */
    TkIncludePoint, /* 43 */
    TkInOutEvents, /* 44 */
    TkInstallFrameMenu, /* 45 */
    TkKeysymToString, /* 46 */
    TkLineToArea, /* 47 */
    TkLineToPoint, /* 48 */
    TkMakeBezierCurve, /* 49 */
    TkMakeBezierPostscript, /* 50 */
    TkOptionClassChanged, /* 51 */
    TkOptionDeadWindow, /* 52 */
    TkOvalToArea, /* 53 */
    TkOvalToPoint, /* 54 */
    TkpChangeFocus, /* 55 */
    TkpCloseDisplay, /* 56 */
    TkpClaimFocus, /* 57 */
    TkpDisplayWarning, /* 58 */
    TkpGetAppName, /* 59 */
    TkpGetOtherWindow, /* 60 */
    TkpGetWrapperWindow, /* 61 */
    TkpInit, /* 62 */
    TkpInitializeMenuBindings, /* 63 */
    TkpMakeContainer, /* 64 */
    TkpMakeMenuWindow, /* 65 */
    TkpMakeWindow, /* 66 */
    TkpMenuNotifyToplevelCreate, /* 67 */
    TkpOpenDisplay, /* 68 */
    TkPointerEvent, /* 69 */
    TkPolygonToArea, /* 70 */
    TkPolygonToPoint, /* 71 */
    TkPositionInTree, /* 72 */
    TkpRedirectKeyEvent, /* 73 */
    TkpSetMainMenubar, /* 74 */
    TkpUseWindow, /* 75 */
    TkpWindowWasRecentlyDeleted, /* 76 */
    TkQueueEventForAllChildren, /* 77 */
    TkReadBitmapFile, /* 78 */
    TkScrollWindow, /* 79 */
    TkSelDeadWindow, /* 80 */
    TkSelEventProc, /* 81 */
    TkSelInit, /* 82 */
    TkSelPropProc, /* 83 */
    TkSetClassProcs, /* 84 */
    TkSetWindowMenuBar, /* 85 */
    TkStringToKeysym, /* 86 */
    TkThickPolyLineToArea, /* 87 */
    TkWmAddToColormapWindows, /* 88 */
    TkWmDeadWindow, /* 89 */
    TkWmFocusToplevel, /* 90 */
    TkWmMapWindow, /* 91 */
    TkWmNewWindow, /* 92 */
    TkWmProtocolEventProc, /* 93 */
    TkWmRemoveFromColormapWindows, /* 94 */
    TkWmRestackToplevel, /* 95 */
    TkWmSetClass, /* 96 */
    TkWmUnmapWindow, /* 97 */
};

extern TkIntStubs *tkIntStubsPtr = &tkIntStubs;

TkIntPlatStubs tkIntPlatStubs = {
    TCL_STUB_MAGIC,
    NULL,
#ifdef __WIN32__
    TkAlignImageData, /* 0 */
    TkClipBox, /* 1 */
    TkCreateRegion, /* 2 */
    TkDestroyRegion, /* 3 */
    TkGenerateActivateEvents, /* 4 */
    TkIntersectRegion, /* 5 */
    TkpGetMS, /* 6 */
    TkPointerDeadWindow, /* 7 */
    TkpPrintWindowId, /* 8 */
    TkpScanWindowId, /* 9 */
    NULL, /* 10 */
    TkpSetCapture, /* 11 */
    TkpSetCursor, /* 12 */
    TkpWmSetState, /* 13 */
    TkRectInRegion, /* 14 */
    TkSetPixmapColormap, /* 15 */
    TkSetRegion, /* 16 */
    TkUnionRectWithRegion, /* 17 */
    TkWinCancelMouseTimer, /* 18 */
    NULL, /* 19 */
    TkWinClipboardRender, /* 20 */
    TkWinEmbeddedEventProc, /* 21 */
    TkWinFillRect, /* 22 */
    TkWinGetBorderPixels, /* 23 */
    TkWinGetDrawableDC, /* 24 */
    TkWinGetModifierState, /* 25 */
    TkWinGetSystemPalette, /* 26 */
    TkWinGetWrapperWindow, /* 27 */
    TkWinHandleMenuEvent, /* 28 */
    TkWinIndexOfColor, /* 29 */
    TkWinPointerDeadWindow, /* 30 */
    TkWinPointerEvent, /* 31 */
    TkWinPointerInit, /* 32 */
    TkWinReflectMessage, /* 33 */
    TkWinReleaseDrawableDC, /* 34 */
    TkWinResendEvent, /* 35 */
    TkWinSelectPalette, /* 36 */
    TkWinSetMenu, /* 37 */
    TkWinSetWindowPos, /* 38 */
    TkWinUpdateCursor, /* 39 */
    TkWinWmCleanup, /* 40 */
    TkWinWmFindEmbedAssociation, /* 41 */
    TkWinWmStoreEmbedAssociation, /* 42 */
    TkWinXCleanup, /* 43 */
    TkWinXInit, /* 44 */
#endif /* __WIN32__ */
#if !defined(__WIN32__) && !defined(MAC_TCL)
    TkCreateXEventSource, /* 0 */
    TkFreeWindowId, /* 1 */
    TkInitXId, /* 2 */
    TkpCmapStressed, /* 3 */
    TkpSync, /* 4 */
    TkUnixContainerId, /* 5 */
    TkUnixDoOneXEvent, /* 6 */
    TkUnixSetMenubar, /* 7 */
#endif /* UNIX */
#ifdef MAC_TCL
    TkClipBox, /* 0 */
    TkCreateRegion, /* 1 */
    TkDestroyRegion, /* 2 */
    TkGenerateActivateEvents, /* 3 */
    TkIntersectRegion, /* 4 */
    TkpCreateNativeBitmap, /* 5 */
    TkpDefineNativeBitmaps, /* 6 */
    TkpGetMS, /* 7 */
    TkpGetNativeAppBitmap, /* 8 */
    TkPointerDeadWindow, /* 9 */
    TkpSetCapture, /* 10 */
    TkpSetCursor, /* 11 */
    NULL, /* 12 */
    TkpWmSetState, /* 13 */
    TkRectInRegion, /* 14 */
    TkSetRegion, /* 15 */
    TkUnionRectWithRegion, /* 16 */
    HandleWMEvent, /* 17 */
    TkAboutDlg, /* 18 */
    TkCreateMacEventSource, /* 19 */
    TkFontList, /* 20 */
    TkGetTransientMaster, /* 21 */
    TkGenerateButtonEvent, /* 22 */
    TkGetCharPositions, /* 23 */
    TkGenWMDestroyEvent, /* 24 */
    TkGenWMConfigureEvent, /* 25 */
    TkMacButtonKeyState, /* 26 */
    TkMacClearMenubarActive, /* 27 */
    TkMacConvertEvent, /* 28 */
    TkMacDispatchMenuEvent, /* 29 */
    TkMacInstallCursor, /* 30 */
    TkMacConvertTkEvent, /* 31 */
    TkMacHandleTearoffMenu, /* 32 */
    tkMacInstallMWConsole, /* 33 */
    TkMacInvalClipRgns, /* 34 */
    TkMacDoHLEvent, /* 35 */
    TkMacFontInfo, /* 36 */
    TkMacGenerateTime, /* 37 */
    TkMacGetDrawablePort, /* 38 */
    TkMacGetScrollbarGrowWindow, /* 39 */
    TkMacGetXWindow, /* 40 */
    TkMacGrowToplevel, /* 41 */
    TkMacHandleMenuSelect, /* 42 */
    TkMacHaveAppearance, /* 43 */
    TkMacInitAppleEvents, /* 44 */
    TkMacInitMenus, /* 45 */
    TkMacInvalidateWindow, /* 46 */
    TkMacIsCharacterMissing, /* 47 */
    TkMacMakeRealWindowExist, /* 48 */
    TkMacMakeStippleMap, /* 49 */
    TkMacMenuClick, /* 50 */
    TkMacRegisterOffScreenWindow, /* 51 */
    TkMacResizable, /* 52 */
    TkMacSetEmbedRgn, /* 53 */
    TkMacSetHelpMenuItemCount, /* 54 */
    TkMacSetScrollbarGrow, /* 55 */
    TkMacSetUpClippingRgn, /* 56 */
    TkMacSetUpGraphicsPort, /* 57 */
    TkMacUpdateClipRgn, /* 58 */
    TkMacUnregisterMacWindow, /* 59 */
    TkMacUseMenuID, /* 60 */
    TkMacVisableClipRgn, /* 61 */
    TkMacWinBounds, /* 62 */
    TkMacWindowOffset, /* 63 */
    TkResumeClipboard, /* 64 */
    TkSetMacColor, /* 65 */
    TkSetWMName, /* 66 */
    TkSuspendClipboard, /* 67 */
    TkWMGrowToplevel, /* 68 */
    TkMacZoomToplevel, /* 69 */
    Tk_TopCoordsToWindow, /* 70 */
    TkMacContainerId, /* 71 */
    TkMacGetHostToplevel, /* 72 */
#endif /* MAC_TCL */
};

extern TkIntPlatStubs *tkIntPlatStubsPtr = &tkIntPlatStubs;

TkIntXlibStubs tkIntXlibStubs = {
    TCL_STUB_MAGIC,
    NULL,
#ifdef __WIN32__
    XGetModifierMapping, /* 0 */
    XCreateImage, /* 1 */
    XGetImage, /* 2 */
    XGetAtomName, /* 3 */
    XKeysymToString, /* 4 */
    XCreateColormap, /* 5 */
    XCreatePixmapCursor, /* 6 */
    XCreateGlyphCursor, /* 7 */
    XGContextFromGC, /* 8 */
    XListHosts, /* 9 */
    XKeycodeToKeysym, /* 10 */
    XStringToKeysym, /* 11 */
    XRootWindow, /* 12 */
    XSetErrorHandler, /* 13 */
    XIconifyWindow, /* 14 */
    XWithdrawWindow, /* 15 */
    XGetWMColormapWindows, /* 16 */
    XAllocColor, /* 17 */
    XBell, /* 18 */
    XChangeProperty, /* 19 */
    XChangeWindowAttributes, /* 20 */
    XClearWindow, /* 21 */
    XConfigureWindow, /* 22 */
    XCopyArea, /* 23 */
    XCopyPlane, /* 24 */
    XDefineCursor, /* 25 */
    XDeleteProperty, /* 26 */
    XDestroyWindow, /* 27 */
    XDrawArc, /* 28 */
    XDrawLines, /* 29 */
    XDrawRectangle, /* 30 */
    XFillArc, /* 31 */
    XFillPolygon, /* 32 */
    XFillRectangles, /* 33 */
    XForceScreenSaver, /* 34 */
    XFreeColormap, /* 35 */
    XFreeColors, /* 36 */
    XFreeCursor, /* 37 */
    XFreeModifiermap, /* 38 */
    XGetGeometry, /* 39 */
    XGetInputFocus, /* 40 */
    XGetWindowProperty, /* 41 */
    XGetWindowAttributes, /* 42 */
    XGrabKeyboard, /* 43 */
    XGrabPointer, /* 44 */
    XKeysymToKeycode, /* 45 */
    XLookupColor, /* 46 */
    XMapWindow, /* 47 */
    XMoveResizeWindow, /* 48 */
    XMoveWindow, /* 49 */
    XNextEvent, /* 50 */
    XPutBackEvent, /* 51 */
    XQueryColors, /* 52 */
    XQueryPointer, /* 53 */
    XQueryTree, /* 54 */
    XRaiseWindow, /* 55 */
    XRefreshKeyboardMapping, /* 56 */
    XResizeWindow, /* 57 */
    XSelectInput, /* 58 */
    XSendEvent, /* 59 */
    XSetCommand, /* 60 */
    XSetIconName, /* 61 */
    XSetInputFocus, /* 62 */
    XSetSelectionOwner, /* 63 */
    XSetWindowBackground, /* 64 */
    XSetWindowBackgroundPixmap, /* 65 */
    XSetWindowBorder, /* 66 */
    XSetWindowBorderPixmap, /* 67 */
    XSetWindowBorderWidth, /* 68 */
    XSetWindowColormap, /* 69 */
    XTranslateCoordinates, /* 70 */
    XUngrabKeyboard, /* 71 */
    XUngrabPointer, /* 72 */
    XUnmapWindow, /* 73 */
    XWindowEvent, /* 74 */
    XDestroyIC, /* 75 */
    XFilterEvent, /* 76 */
    XmbLookupString, /* 77 */
    TkPutImage, /* 78 */
#endif /* __WIN32__ */
#ifdef MAC_TCL
    NULL, /* 0 */
    NULL, /* 1 */
    NULL, /* 2 */
    NULL, /* 3 */
    NULL, /* 4 */
    NULL, /* 5 */
    NULL, /* 6 */
    NULL, /* 7 */
    NULL, /* 8 */
    NULL, /* 9 */
    NULL, /* 10 */
    NULL, /* 11 */
    NULL, /* 12 */
    NULL, /* 13 */
    NULL, /* 14 */
    NULL, /* 15 */
    NULL, /* 16 */
    NULL, /* 17 */
    NULL, /* 18 */
    NULL, /* 19 */
    NULL, /* 20 */
    NULL, /* 21 */
    NULL, /* 22 */
    NULL, /* 23 */
    NULL, /* 24 */
    NULL, /* 25 */
    NULL, /* 26 */
    NULL, /* 27 */
    NULL, /* 28 */
    NULL, /* 29 */
    NULL, /* 30 */
    NULL, /* 31 */
    NULL, /* 32 */
    NULL, /* 33 */
    NULL, /* 34 */
    NULL, /* 35 */
    NULL, /* 36 */
    NULL, /* 37 */
    NULL, /* 38 */
    NULL, /* 39 */
    NULL, /* 40 */
    NULL, /* 41 */
    NULL, /* 42 */
    NULL, /* 43 */
    NULL, /* 44 */
    NULL, /* 45 */
    NULL, /* 46 */
    NULL, /* 47 */
    NULL, /* 48 */
    NULL, /* 49 */
    NULL, /* 50 */
    NULL, /* 51 */
    NULL, /* 52 */
    NULL, /* 53 */
    NULL, /* 54 */
    NULL, /* 55 */
    NULL, /* 56 */
    NULL, /* 57 */
    NULL, /* 58 */
    NULL, /* 59 */
    NULL, /* 60 */
    NULL, /* 61 */
    NULL, /* 62 */
    NULL, /* 63 */
    NULL, /* 64 */
    NULL, /* 65 */
    NULL, /* 66 */
    NULL, /* 67 */
    NULL, /* 68 */
    NULL, /* 69 */
    NULL, /* 70 */
    NULL, /* 71 */
    NULL, /* 72 */
    NULL, /* 73 */
    NULL, /* 74 */
    NULL, /* 75 */
    NULL, /* 76 */
    NULL, /* 77 */
    XGetModifierMapping, /* 78 */
    XCreateImage, /* 79 */
    XGetImage, /* 80 */
    XGetAtomName, /* 81 */
    XKeysymToString, /* 82 */
    XCreateColormap, /* 83 */
    NULL, /* 84 */
    NULL, /* 85 */
    XGContextFromGC, /* 86 */
    NULL, /* 87 */
    XKeycodeToKeysym, /* 88 */
    XStringToKeysym, /* 89 */
    XRootWindow, /* 90 */
    XSetErrorHandler, /* 91 */
    NULL, /* 92 */
    NULL, /* 93 */
    NULL, /* 94 */
    XAllocColor, /* 95 */
    XBell, /* 96 */
    XChangeProperty, /* 97 */
    XChangeWindowAttributes, /* 98 */
    NULL, /* 99 */
    XConfigureWindow, /* 100 */
    XCopyArea, /* 101 */
    XCopyPlane, /* 102 */
    XDefineCursor, /* 103 */
    NULL, /* 104 */
    XDestroyWindow, /* 105 */
    XDrawArc, /* 106 */
    XDrawLines, /* 107 */
    XDrawRectangle, /* 108 */
    XFillArc, /* 109 */
    XFillPolygon, /* 110 */
    XFillRectangles, /* 111 */
    NULL, /* 112 */
    XFreeColormap, /* 113 */
    XFreeColors, /* 114 */
    NULL, /* 115 */
    XFreeModifiermap, /* 116 */
    XGetGeometry, /* 117 */
    NULL, /* 118 */
    XGetWindowProperty, /* 119 */
    NULL, /* 120 */
    XGrabKeyboard, /* 121 */
    XGrabPointer, /* 122 */
    XKeysymToKeycode, /* 123 */
    NULL, /* 124 */
    XMapWindow, /* 125 */
    XMoveResizeWindow, /* 126 */
    XMoveWindow, /* 127 */
    NULL, /* 128 */
    NULL, /* 129 */
    NULL, /* 130 */
    XQueryPointer, /* 131 */
    NULL, /* 132 */
    XRaiseWindow, /* 133 */
    XRefreshKeyboardMapping, /* 134 */
    XResizeWindow, /* 135 */
    XSelectInput, /* 136 */
    XSendEvent, /* 137 */
    NULL, /* 138 */
    XSetIconName, /* 139 */
    XSetInputFocus, /* 140 */
    XSetSelectionOwner, /* 141 */
    XSetWindowBackground, /* 142 */
    XSetWindowBackgroundPixmap, /* 143 */
    XSetWindowBorder, /* 144 */
    XSetWindowBorderPixmap, /* 145 */
    XSetWindowBorderWidth, /* 146 */
    XSetWindowColormap, /* 147 */
    NULL, /* 148 */
    XUngrabKeyboard, /* 149 */
    XUngrabPointer, /* 150 */
    XUnmapWindow, /* 151 */
    NULL, /* 152 */
    NULL, /* 153 */
    NULL, /* 154 */
    NULL, /* 155 */
    TkPutImage, /* 156 */
#endif /* MAC_TCL */
};

extern TkIntXlibStubs *tkIntXlibStubsPtr = &tkIntXlibStubs;

TkPlatStubs tkPlatStubs = {
    TCL_STUB_MAGIC,
    NULL,
#ifdef __WIN32__
    Tk_AttachHWND, /* 0 */
    Tk_GetHINSTANCE, /* 1 */
    Tk_GetHWND, /* 2 */
    Tk_HWNDToWindow, /* 3 */
    Tk_PointerEvent, /* 4 */
    Tk_TranslateWinEvent, /* 5 */
#endif /* __WIN32__ */
#ifdef MAC_TCL
    Tk_MacSetEmbedHandler, /* 0 */
    Tk_MacTurnOffMenus, /* 1 */
    Tk_MacTkOwnsCursor, /* 2 */
    TkMacInitMenus, /* 3 */
    TkMacInitAppleEvents, /* 4 */
    TkMacConvertEvent, /* 5 */
    TkMacConvertTkEvent, /* 6 */
    TkGenWMConfigureEvent, /* 7 */
    TkMacInvalClipRgns, /* 8 */
    TkMacHaveAppearance, /* 9 */
    TkMacGetDrawablePort, /* 10 */
#endif /* MAC_TCL */
};

extern TkPlatStubs *tkPlatStubsPtr = &tkPlatStubs;

static TkStubHooks tkStubHooks = {
    &tkPlatStubs,
    &tkIntStubs,
    &tkIntPlatStubs,
    &tkIntXlibStubs
};


/* !END!: Do not edit above this line. */
